const ZH_CN_PRODUCT_IA_REDIRECTS: Record<string, string> = {
  'realtime-media/recording': '/zh-CN/realtime-media/cloud-recording',
  'realtime-media/danmaku/api/api-limits':
    '/zh-CN/realtime-media/danmaku/reference/api-limits',
  'realtime-media/danmaku/api/base-url':
    '/zh-CN/realtime-media/danmaku/reference/base-url',
  'realtime-media/danmaku/get-started/authorization':
    '/zh-CN/realtime-media/danmaku/build/setup-and-access/authorization',
  'realtime-media/danmaku/get-started/enable-service':
    '/zh-CN/realtime-media/danmaku/build/setup-and-access/enable-service',
  'realtime-media/danmaku/overview/billing':
    '/zh-CN/realtime-media/danmaku/reference/billing',
  'realtime-media/danmaku/overview/product-overview':
    '/zh-CN/realtime-media/danmaku',
  'realtime-media/danmaku/overview/release-notes':
    '/zh-CN/realtime-media/danmaku/reference/release-notes',
  'realtime-media/danmaku/resources':
    '/zh-CN/realtime-media/danmaku/reference/downloads',
  'realtime-media/danmaku/response-code':
    '/zh-CN/realtime-media/danmaku/reference/response-code',
  'realtime-media/fusion-cdn/api/reference':
    '/zh-CN/realtime-media/fusion-cdn/reference/api-reference',
  'realtime-media/fusion-cdn/best-practices/rest-availability':
    '/zh-CN/realtime-media/fusion-cdn/build/optimize-and-operate/rest-availability',
  'realtime-media/fusion-cdn/get-started/enable-service':
    '/zh-CN/realtime-media/fusion-cdn/build/setup-and-access/enable-service',
  'realtime-media/fusion-cdn/overview/billing':
    '/zh-CN/realtime-media/fusion-cdn/reference/billing',
  'realtime-media/fusion-cdn/overview/product-overview':
    '/zh-CN/realtime-media/fusion-cdn',
  'realtime-media/fusion-cdn/quota':
    '/zh-CN/realtime-media/fusion-cdn/reference/quota',
  'realtime-media/fusion-cdn/response-code':
    '/zh-CN/realtime-media/fusion-cdn/reference/response-code',
  'realtime-media/fusion-cdn/user-guides/analytics':
    '/zh-CN/realtime-media/fusion-cdn/build/optimize-and-operate/analytics',
  'realtime-media/fusion-cdn/user-guides/http-hmac-auth':
    '/zh-CN/realtime-media/fusion-cdn/build/setup-and-access/http-hmac-auth',
  'realtime-media/fusion-cdn/user-guides/obs-config':
    '/zh-CN/realtime-media/fusion-cdn/build/setup-and-access/obs-config',
  'realtime-media/fusion-cdn/user-guides/stream-recording':
    '/zh-CN/realtime-media/fusion-cdn/build/optimize-and-operate/stream-recording',
  'realtime-media/fusion-cdn/user-guides/streaming-url':
    '/zh-CN/realtime-media/fusion-cdn/build/manage-media-streams/streaming-url',
  'realtime-media/fusion-cdn/webhook/enable-ncs':
    '/zh-CN/realtime-media/fusion-cdn/build/monitor-events/enable-ncs',
  'realtime-media/fusion-cdn/webhook/ncs-event':
    '/zh-CN/realtime-media/fusion-cdn/reference/ncs-event',
  'realtime-media/marketplace/create-extensions/audio-filter':
    '/zh-CN/realtime-media/marketplace/build/create-extensions/audio-filter',
  'realtime-media/marketplace/create-extensions/concepts':
    '/zh-CN/realtime-media/marketplace/reference/concepts',
  'realtime-media/marketplace/create-extensions/doc-template':
    '/zh-CN/realtime-media/marketplace/build/create-extensions/doc-template',
  'realtime-media/marketplace/create-extensions/provisioning':
    '/zh-CN/realtime-media/marketplace/reference/provisioning',
  'realtime-media/marketplace/create-extensions/publish':
    '/zh-CN/realtime-media/marketplace/build/create-extensions/publish',
  'realtime-media/marketplace/create-extensions/signature-algorithm':
    '/zh-CN/realtime-media/marketplace/build/create-extensions/signature-algorithm',
  'realtime-media/marketplace/create-extensions/test':
    '/zh-CN/realtime-media/marketplace/build/create-extensions/test',
  'realtime-media/marketplace/create-extensions/usage-billing':
    '/zh-CN/realtime-media/marketplace/reference/usage-billing',
  'realtime-media/marketplace/create-extensions/video-filter':
    '/zh-CN/realtime-media/marketplace/build/create-extensions/video-filter',
  'realtime-media/marketplace/integrate-extensions/audio-moderation-api':
    '/zh-CN/realtime-media/marketplace/build/integrate-extensions/audio-moderation-api',
  'realtime-media/marketplace/integrate-extensions/faceunity-ar':
    '/zh-CN/realtime-media/marketplace/build/integrate-extensions/faceunity-ar',
  'realtime-media/marketplace/integrate-extensions/faceunity-ar-api':
    '/zh-CN/realtime-media/marketplace/reference/faceunity-ar-api',
  'realtime-media/marketplace/integrate-extensions/iflytek-asr':
    '/zh-CN/realtime-media/marketplace/build/integrate-extensions/iflytek-asr',
  'realtime-media/marketplace/integrate-extensions/iflytek-asr-api':
    '/zh-CN/realtime-media/marketplace/reference/iflytek-asr-api',
  'realtime-media/marketplace/integrate-extensions/kivisense-beautify':
    '/zh-CN/realtime-media/marketplace/build/integrate-extensions/kivisense-beautify',
  'realtime-media/marketplace/integrate-extensions/netease-yidun-video-moderation':
    '/zh-CN/realtime-media/marketplace/build/integrate-extensions/netease-yidun-video-moderation',
  'realtime-media/marketplace/integrate-extensions/picup':
    '/zh-CN/realtime-media/marketplace/build/integrate-extensions/picup',
  'realtime-media/marketplace/integrate-extensions/sensetime-ar':
    '/zh-CN/realtime-media/marketplace/build/integrate-extensions/sensetime-ar',
  'realtime-media/marketplace/integrate-extensions/sensetime-ar-api':
    '/zh-CN/realtime-media/marketplace/reference/sensetime-ar-api',
  'realtime-media/marketplace/integrate-extensions/shengwang-ai-meeting-notes':
    '/zh-CN/realtime-media/marketplace/build/integrate-extensions/shengwang-ai-meeting-notes',
  'realtime-media/marketplace/integrate-extensions/shengwang-ai-meeting-notes-api':
    '/zh-CN/realtime-media/marketplace/reference/shengwang-ai-meeting-notes-api',
  'realtime-media/marketplace/integrate-extensions/yitutech-audio-moderation':
    '/zh-CN/realtime-media/marketplace/build/integrate-extensions/yitutech-audio-moderation',
  'realtime-media/marketplace/overview/product-overview':
    '/zh-CN/realtime-media/marketplace',
  'realtime-media/media-pull/api/video-profile':
    '/zh-CN/realtime-media/media-pull/reference/video-profile',
  'realtime-media/media-pull/best-practices/checklist':
    '/zh-CN/realtime-media/media-pull/build/optimize-and-operate/checklist',
  'realtime-media/media-pull/best-practices/ensure-player-created':
    '/zh-CN/realtime-media/media-pull/build/optimize-and-operate/ensure-player-created',
  'realtime-media/media-pull/best-practices/rest-availability':
    '/zh-CN/realtime-media/media-pull/build/optimize-and-operate/rest-availability',
  'realtime-media/media-pull/get-started/call-api':
    '/zh-CN/realtime-media/media-pull/build/setup-and-access/call-api',
  'realtime-media/media-pull/get-started/enable-service':
    '/zh-CN/realtime-media/media-pull/build/setup-and-access/enable-service',
  'realtime-media/media-pull/overview/billing':
    '/zh-CN/realtime-media/media-pull/reference/billing',
  'realtime-media/media-pull/overview/payment':
    '/zh-CN/realtime-media/media-pull/reference/payment',
  'realtime-media/media-pull/overview/product-overview':
    '/zh-CN/realtime-media/media-pull',
  'realtime-media/media-pull/overview/release-notes':
    '/zh-CN/realtime-media/media-pull/reference/release-notes',
  'realtime-media/media-pull/quota':
    '/zh-CN/realtime-media/media-pull/reference/quota',
  'realtime-media/media-pull/response-code':
    '/zh-CN/realtime-media/media-pull/reference/response-code',
  'realtime-media/media-pull/user-guides/http-basic-auth':
    '/zh-CN/realtime-media/media-pull/build/setup-and-access/http-basic-auth',
  'realtime-media/media-pull/webhook/enable-event-notification':
    '/zh-CN/realtime-media/media-pull/build/monitor-events/enable-event-notification',
  'realtime-media/media-pull/webhook/ncs-events':
    '/zh-CN/realtime-media/media-pull/reference/ncs-events',
  'realtime-media/media-push/api/video-profile':
    '/zh-CN/realtime-media/media-push/reference/video-profile',
  'realtime-media/media-push/best-practices/checklist':
    '/zh-CN/realtime-media/media-push/build/optimize-and-operate/checklist',
  'realtime-media/media-push/best-practices/ensure-converter-created':
    '/zh-CN/realtime-media/media-push/build/optimize-and-operate/ensure-converter-created',
  'realtime-media/media-push/best-practices/rest-availability':
    '/zh-CN/realtime-media/media-push/build/optimize-and-operate/rest-availability',
  'realtime-media/media-push/get-started/call-api':
    '/zh-CN/realtime-media/media-push/build/setup-and-access/call-api',
  'realtime-media/media-push/get-started/enable-service':
    '/zh-CN/realtime-media/media-push/build/setup-and-access/enable-service',
  'realtime-media/media-push/overview/billing':
    '/zh-CN/realtime-media/media-push/reference/billing',
  'realtime-media/media-push/overview/payment':
    '/zh-CN/realtime-media/media-push/reference/payment',
  'realtime-media/media-push/overview/product-overview':
    '/zh-CN/realtime-media/media-push',
  'realtime-media/media-push/quota':
    '/zh-CN/realtime-media/media-push/reference/quota',
  'realtime-media/media-push/response-code':
    '/zh-CN/realtime-media/media-push/reference/response-code',
  'realtime-media/media-push/user-guides/http-basic-auth':
    '/zh-CN/realtime-media/media-push/build/setup-and-access/http-basic-auth',
  'realtime-media/media-push/user-guides/set-no-transcode':
    '/zh-CN/realtime-media/media-push/build/manage-media-streams/set-no-transcode',
  'realtime-media/media-push/user-guides/set-sei':
    '/zh-CN/realtime-media/media-push/build/manage-media-streams/set-sei',
  'realtime-media/media-push/user-guides/set-transcode':
    '/zh-CN/realtime-media/media-push/build/manage-media-streams/set-transcode',
  'realtime-media/media-push/user-guides/set-volume':
    '/zh-CN/realtime-media/media-push/build/manage-media-streams/set-volume',
  'realtime-media/media-push/user-guides/update-transcode':
    '/zh-CN/realtime-media/media-push/build/manage-media-streams/update-transcode',
  'realtime-media/media-push/user-guides/vertical-streaming':
    '/zh-CN/realtime-media/media-push/build/manage-media-streams/vertical-streaming',
  'realtime-media/media-push/webhook/enable-ncs':
    '/zh-CN/realtime-media/media-push/build/monitor-events/enable-ncs',
  'realtime-media/media-push/webhook/ncs-events':
    '/zh-CN/realtime-media/media-push/reference/ncs-events',
  'realtime-media/online-ktv/auikaraoke/advanced-features/lyrics-scoring':
    '/zh-CN/solutions/online-ktv/auikaraoke/build/extend-karaoke/lyrics-scoring',
  'realtime-media/online-ktv/auikaraoke/advanced-features/lyrics-syncing':
    '/zh-CN/solutions/online-ktv/auikaraoke/build/extend-karaoke/lyrics-syncing',
  'realtime-media/online-ktv/auikaraoke/api/auikaraoke-api':
    '/zh-CN/api-reference/online-ktv/android/auikaraoke/api/auikaraoke-api',
  'realtime-media/online-ktv/auikaraoke/api/lyrics-api':
    '/zh-CN/api-reference/online-ktv/android/auikaraoke/api/lyrics-api',
  'realtime-media/online-ktv/auikaraoke/get-started/enable-service':
    '/zh-CN/solutions/online-ktv/auikaraoke/build/setup-and-access/enable-service',
  'realtime-media/online-ktv/auikaraoke/get-started/run-github-project-backend':
    '/zh-CN/solutions/online-ktv/auikaraoke/build/manage-karaoke/run-github-project-backend',
  'realtime-media/online-ktv/auikaraoke/overview/billing':
    '/zh-CN/solutions/online-ktv/auikaraoke/reference/billing',
  'realtime-media/online-ktv/auikaraoke/overview/introduction':
    '/zh-CN/solutions/online-ktv/auikaraoke',
  'realtime-media/online-ktv/auikaraoke/overview/solution-compare':
    '/zh-CN/solutions/online-ktv/auikaraoke/reference/solution-compare',
  'realtime-media/online-ktv/auikaraoke/overview/uikitkaraoke':
    '/zh-CN/solutions/online-ktv/auikaraoke/build/manage-karaoke/uikitkaraoke',
  'realtime-media/online-ktv/auikaraoke/resources':
    '/zh-CN/solutions/online-ktv/auikaraoke/reference/downloads',
  'realtime-media/online-ktv/ktv-scenario/advanced-features/get-music':
    '/zh-CN/solutions/online-ktv/ktv-scenario/build/extend-karaoke/get-music',
  'realtime-media/online-ktv/ktv-scenario/advanced-features/lyrics-scoring':
    '/zh-CN/solutions/online-ktv/ktv-scenario/build/extend-karaoke/lyrics-scoring',
  'realtime-media/online-ktv/ktv-scenario/advanced-features/lyrics-syncing':
    '/zh-CN/solutions/online-ktv/ktv-scenario/build/extend-karaoke/lyrics-syncing',
  'realtime-media/online-ktv/ktv-scenario/api/ktv-api':
    '/zh-CN/api-reference/online-ktv/android/ktv-scenario/api/ktv-api',
  'realtime-media/online-ktv/ktv-scenario/api/lyrics-api':
    '/zh-CN/api-reference/online-ktv/android/ktv-scenario/api/lyrics-api',
  'realtime-media/online-ktv/ktv-scenario/api/music-content-center':
    '/zh-CN/api-reference/online-ktv/android/ktv-scenario/api/music-content-center',
  'realtime-media/online-ktv/ktv-scenario/api/rtc-api':
    '/zh-CN/api-reference/online-ktv/android/ktv-scenario/api/rtc-api',
  'realtime-media/online-ktv/ktv-scenario/get-started/enable-service':
    '/zh-CN/solutions/online-ktv/ktv-scenario/build/setup-and-access/enable-service',
  'realtime-media/online-ktv/ktv-scenario/implementation/chorus':
    '/zh-CN/solutions/online-ktv/ktv-scenario/build/implementation/chorus',
  'realtime-media/online-ktv/ktv-scenario/implementation/gaming':
    '/zh-CN/solutions/online-ktv/ktv-scenario/build/implementation/gaming',
  'realtime-media/online-ktv/ktv-scenario/implementation/grand-chorus':
    '/zh-CN/solutions/online-ktv/ktv-scenario/build/implementation/grand-chorus',
  'realtime-media/online-ktv/ktv-scenario/implementation/relay':
    '/zh-CN/solutions/online-ktv/ktv-scenario/build/implementation/relay',
  'realtime-media/online-ktv/ktv-scenario/implementation/solo':
    '/zh-CN/solutions/online-ktv/ktv-scenario/build/implementation/solo',
  'realtime-media/online-ktv/ktv-scenario/overview/billing':
    '/zh-CN/solutions/online-ktv/ktv-scenario/reference/billing',
  'realtime-media/online-ktv/ktv-scenario/overview/introduction':
    '/zh-CN/solutions/online-ktv/ktv-scenario',
  'realtime-media/online-ktv/ktv-scenario/overview/solution-compare':
    '/zh-CN/solutions/online-ktv/ktv-scenario/reference/solution-compare',
  'realtime-media/online-ktv/ktv-scenario/resources':
    '/zh-CN/solutions/online-ktv/ktv-scenario/reference/downloads',
  'realtime-media/online-ktv/online-ktv-sdk/advanced-features/get-music':
    '/zh-CN/solutions/online-ktv/online-ktv-sdk/build/extend-karaoke/get-music',
  'realtime-media/online-ktv/online-ktv-sdk/advanced-features/lyrics-scoring':
    '/zh-CN/solutions/online-ktv/online-ktv-sdk/build/extend-karaoke/lyrics-scoring',
  'realtime-media/online-ktv/online-ktv-sdk/advanced-features/lyrics-syncing':
    '/zh-CN/solutions/online-ktv/online-ktv-sdk/build/extend-karaoke/lyrics-syncing',
  'realtime-media/online-ktv/online-ktv-sdk/api/lyrics-api':
    '/zh-CN/api-reference/online-ktv/android/online-ktv-sdk/api/lyrics-api',
  'realtime-media/online-ktv/online-ktv-sdk/api/music-content-center':
    '/zh-CN/api-reference/online-ktv/android/online-ktv-sdk/api/music-content-center',
  'realtime-media/online-ktv/online-ktv-sdk/api/rtc-api':
    '/zh-CN/api-reference/online-ktv/android/online-ktv-sdk/api/rtc-api',
  'realtime-media/online-ktv/online-ktv-sdk/get-started/enable-service':
    '/zh-CN/solutions/online-ktv/online-ktv-sdk/build/setup-and-access/enable-service',
  'realtime-media/online-ktv/online-ktv-sdk/overview/billing':
    '/zh-CN/solutions/online-ktv/online-ktv-sdk/reference/billing',
  'realtime-media/online-ktv/online-ktv-sdk/overview/introduction':
    '/zh-CN/solutions/online-ktv/online-ktv-sdk',
  'realtime-media/online-ktv/online-ktv-sdk/overview/solution-compare':
    '/zh-CN/solutions/online-ktv/online-ktv-sdk/reference/solution-compare',
  'realtime-media/online-ktv/online-ktv-sdk/resources':
    '/zh-CN/solutions/online-ktv/online-ktv-sdk/reference/downloads',
  'realtime-media/recording/cloud-recording/api/reference':
    '/zh-CN/realtime-media/cloud-recording/reference/api-reference',
  'realtime-media/recording/cloud-recording/best-practices/checklist':
    '/zh-CN/realtime-media/cloud-recording/build/optimize-and-operate/checklist',
  'realtime-media/recording/cloud-recording/best-practices/recording-status':
    '/zh-CN/realtime-media/cloud-recording/build/optimize-and-operate/recording-status',
  'realtime-media/recording/cloud-recording/best-practices/rest-availability':
    '/zh-CN/realtime-media/cloud-recording/build/optimize-and-operate/rest-availability',
  'realtime-media/recording/cloud-recording/best-practices/webpage':
    '/zh-CN/realtime-media/cloud-recording/build/optimize-and-operate/webpage',
  'realtime-media/recording/cloud-recording/get-started/enable-service':
    '/zh-CN/realtime-media/cloud-recording/build/setup-and-access/enable-service',
  'realtime-media/recording/cloud-recording/get-started/quick-start-nodejs':
    '/zh-CN/realtime-media/cloud-recording/build/implement-core-features/quick-start-nodejs',
  'realtime-media/recording/cloud-recording/overview/billing-strategy/billing':
    '/zh-CN/realtime-media/cloud-recording/reference/billing-strategy/billing',
  'realtime-media/recording/cloud-recording/overview/billing-strategy/payment':
    '/zh-CN/realtime-media/cloud-recording/reference/billing-strategy/payment',
  'realtime-media/recording/cloud-recording/overview/billing-strategy/snapshot-billing':
    '/zh-CN/realtime-media/cloud-recording/reference/billing-strategy/snapshot-billing',
  'realtime-media/recording/cloud-recording/overview/billing-strategy/webpage-billing':
    '/zh-CN/realtime-media/cloud-recording/reference/billing-strategy/webpage-billing',
  'realtime-media/recording/cloud-recording/overview/concepts':
    '/zh-CN/realtime-media/cloud-recording/reference/concepts',
  'realtime-media/recording/cloud-recording/overview/product-overview':
    '/zh-CN/realtime-media/cloud-recording',
  'realtime-media/recording/cloud-recording/overview/release-notes':
    '/zh-CN/realtime-media/cloud-recording/reference/release-notes',
  'realtime-media/recording/cloud-recording/quota':
    '/zh-CN/realtime-media/cloud-recording/reference/quota',
  'realtime-media/recording/cloud-recording/response-code':
    '/zh-CN/realtime-media/cloud-recording/reference/response-code',
  'realtime-media/recording/cloud-recording/user-guides/http-basic-auth':
    '/zh-CN/realtime-media/cloud-recording/build/setup-and-access/http-basic-auth',
  'realtime-media/recording/cloud-recording/user-guides/individual-mode/set-individual':
    '/zh-CN/realtime-media/cloud-recording/build/recording-modes/individual-mode/set-individual',
  'realtime-media/recording/cloud-recording/user-guides/individual-mode/set-individual-without-transcoding':
    '/zh-CN/realtime-media/cloud-recording/build/recording-modes/individual-mode/set-individual-without-transcoding',
  'realtime-media/recording/cloud-recording/user-guides/manage-file/convert-format':
    '/zh-CN/realtime-media/cloud-recording/build/manage-recorded-files/convert-format',
  'realtime-media/recording/cloud-recording/user-guides/manage-file/introduce-recorded-files':
    '/zh-CN/realtime-media/cloud-recording/build/manage-recorded-files/introduce-recorded-files',
  'realtime-media/recording/cloud-recording/user-guides/manage-file/play-online':
    '/zh-CN/realtime-media/cloud-recording/build/manage-recorded-files/play-online',
  'realtime-media/recording/cloud-recording/user-guides/manage-file/playback':
    '/zh-CN/realtime-media/cloud-recording/build/manage-recorded-files/playback',
  'realtime-media/recording/cloud-recording/user-guides/mix-mode/set-composite':
    '/zh-CN/realtime-media/cloud-recording/build/recording-modes/mix-mode/set-composite',
  'realtime-media/recording/cloud-recording/user-guides/mix-mode/set-composite-layout':
    '/zh-CN/realtime-media/cloud-recording/build/recording-modes/mix-mode/set-composite-layout',
  'realtime-media/recording/cloud-recording/user-guides/snapshot':
    '/zh-CN/realtime-media/cloud-recording/build/recording-modes/snapshot',
  'realtime-media/recording/cloud-recording/user-guides/web-mode/set-webpage-recording':
    '/zh-CN/realtime-media/cloud-recording/build/recording-modes/web-mode/set-webpage-recording',
  'realtime-media/recording/cloud-recording/webhook/enable-ncs':
    '/zh-CN/realtime-media/cloud-recording/build/monitor-events/enable-ncs',
  'realtime-media/recording/cloud-recording/webhook/ncs-events':
    '/zh-CN/realtime-media/cloud-recording/reference/ncs-events',
  'realtime-media/recording/cloud-recording/webhook/service':
    '/zh-CN/realtime-media/cloud-recording/build/implement-core-features/service',
  'realtime-media/recording/cloud-recording/webhook/status':
    '/zh-CN/realtime-media/cloud-recording/build/implement-core-features/status',
  'realtime-media/recording/cloud-recording/webhook/uploading':
    '/zh-CN/realtime-media/cloud-recording/build/implement-core-features/uploading',
  'realtime-media/recording/cloud-recording/webhook/webpage':
    '/zh-CN/realtime-media/cloud-recording/build/implement-core-features/webpage',
  'realtime-media/recording/local-server-recording/best-practice/restore-files':
    '/zh-CN/realtime-media/local-server-recording/build/optimize-and-operate/restore-files',
  'realtime-media/recording/local-server-recording/get-started/enable-service':
    '/zh-CN/realtime-media/local-server-recording/build/setup-and-access/enable-service',
  'realtime-media/recording/local-server-recording/legacy/collect-logs':
    '/zh-CN/realtime-media/local-server-recording/build/optimize-and-operate/legacy/collect-logs',
  'realtime-media/recording/local-server-recording/legacy/composite-mode':
    '/zh-CN/realtime-media/local-server-recording/build/implement-core-features/legacy/composite-mode',
  'realtime-media/recording/local-server-recording/legacy/docker':
    '/zh-CN/realtime-media/local-server-recording/build/implement-core-features/legacy/docker',
  'realtime-media/recording/local-server-recording/legacy/individual-mode':
    '/zh-CN/realtime-media/local-server-recording/build/implement-core-features/legacy/individual-mode',
  'realtime-media/recording/local-server-recording/legacy/integrate-sdk':
    '/zh-CN/realtime-media/local-server-recording/build/implement-core-features/legacy/integrate-sdk',
  'realtime-media/recording/local-server-recording/legacy/manage-files':
    '/zh-CN/realtime-media/local-server-recording/build/implement-core-features/legacy/manage-files',
  'realtime-media/recording/local-server-recording/legacy/merge-files':
    '/zh-CN/realtime-media/local-server-recording/build/implement-core-features/legacy/merge-files',
  'realtime-media/recording/local-server-recording/legacy/raw-data':
    '/zh-CN/realtime-media/local-server-recording/build/implement-core-features/legacy/raw-data',
  'realtime-media/recording/local-server-recording/legacy/record-by-api':
    '/zh-CN/realtime-media/local-server-recording/build/implement-core-features/record-by-api',
  'realtime-media/recording/local-server-recording/legacy/record-by-cmd':
    '/zh-CN/realtime-media/local-server-recording/build/implement-core-features/legacy/record-by-cmd',
  'realtime-media/recording/local-server-recording/legacy/restore-files':
    '/zh-CN/realtime-media/local-server-recording/build/optimize-and-operate/legacy/restore-files',
  'realtime-media/recording/local-server-recording/legacy/screenshot':
    '/zh-CN/realtime-media/local-server-recording/build/recording-modes/legacy/screenshot',
  'realtime-media/recording/local-server-recording/legacy/set-layout':
    '/zh-CN/realtime-media/local-server-recording/build/recording-modes/legacy/set-layout',
  'realtime-media/recording/local-server-recording/legacy/set-output-video':
    '/zh-CN/realtime-media/local-server-recording/build/implement-core-features/legacy/set-output-video',
  'realtime-media/recording/local-server-recording/legacy/watermark':
    '/zh-CN/realtime-media/local-server-recording/build/recording-modes/legacy/watermark',
  'realtime-media/recording/local-server-recording/overview/billing':
    '/zh-CN/realtime-media/local-server-recording/reference/billing',
  'realtime-media/recording/local-server-recording/overview/migration-guide':
    '/zh-CN/realtime-media/local-server-recording/reference/migration-guide',
  'realtime-media/recording/local-server-recording/overview/payment':
    '/zh-CN/realtime-media/local-server-recording/reference/payment',
  'realtime-media/recording/local-server-recording/overview/product-overview':
    '/zh-CN/realtime-media/local-server-recording',
  'realtime-media/recording/local-server-recording/overview/release-notes':
    '/zh-CN/realtime-media/local-server-recording/reference/release-notes',
  'realtime-media/recording/local-server-recording/overview/sunset':
    '/zh-CN/realtime-media/local-server-recording/reference/sunset',
  'realtime-media/recording/local-server-recording/resources':
    '/zh-CN/realtime-media/local-server-recording/reference/downloads',
  'realtime-media/recording/local-server-recording/user-guides/cloud-proxy':
    '/zh-CN/realtime-media/local-server-recording/build/setup-and-access/cloud-proxy',
  'realtime-media/recording/local-server-recording/user-guides/generate-token':
    '/zh-CN/realtime-media/local-server-recording/build/setup-and-access/generate-token',
  'realtime-media/recording/local-server-recording/user-guides/recording-mode':
    '/zh-CN/realtime-media/local-server-recording/build/recording-modes/recording-mode',
  'realtime-media/recording/local-server-recording/user-guides/screen-capture':
    '/zh-CN/realtime-media/local-server-recording/build/recording-modes/screen-capture',
  'realtime-media/recording/local-server-recording/user-guides/set-layout':
    '/zh-CN/realtime-media/local-server-recording/build/recording-modes/set-layout',
  'realtime-media/recording/local-server-recording/user-guides/watermark':
    '/zh-CN/realtime-media/local-server-recording/build/recording-modes/watermark',
  'realtime-media/rtc-server-sdk/advanced-features/cloud-proxy':
    '/zh-CN/realtime-media/rtc-server-sdk/build/setup-and-access/cloud-proxy',
  'realtime-media/rtc-server-sdk/advanced-features/encryption':
    '/zh-CN/realtime-media/rtc-server-sdk/build/implement-core-features/encryption',
  'realtime-media/rtc-server-sdk/advanced-features/mix-video':
    '/zh-CN/realtime-media/rtc-server-sdk/build/implement-core-features/mix-video',
  'realtime-media/rtc-server-sdk/advanced-features/set-region':
    '/zh-CN/realtime-media/rtc-server-sdk/build/setup-and-access/set-region',
  'realtime-media/rtc-server-sdk/advanced-features/string-uid':
    '/zh-CN/realtime-media/rtc-server-sdk/build/implement-core-features/string-uid',
  'realtime-media/rtc-server-sdk/error-code':
    '/zh-CN/realtime-media/rtc-server-sdk/reference/error-code',
  'realtime-media/rtc-server-sdk/get-started/enable-service':
    '/zh-CN/realtime-media/rtc-server-sdk/build/setup-and-access/enable-service',
  'realtime-media/rtc-server-sdk/get-started/send-receive':
    '/zh-CN/realtime-media/rtc-server-sdk/build/implement-core-features/send-receive',
  'realtime-media/rtc-server-sdk/get-started/send-receive.go':
    '/zh-CN/realtime-media/rtc-server-sdk/build/implement-core-features/send-receive?platform=go',
  'realtime-media/rtc-server-sdk/index.go':
    '/zh-CN/realtime-media/rtc-server-sdk',
  'realtime-media/rtc-server-sdk/overview/product-overview':
    '/zh-CN/realtime-media/rtc-server-sdk',
  'realtime-media/rtc-server-sdk/overview/release-notes':
    '/zh-CN/realtime-media/rtc-server-sdk/reference/release-notes',
  'realtime-media/rtc-server-sdk/overview/release-notes.go':
    '/zh-CN/realtime-media/rtc-server-sdk/reference/release-notes?platform=go',
  'realtime-media/rtc-server-sdk/resources':
    '/zh-CN/realtime-media/rtc-server-sdk/reference/downloads',
  'realtime-media/rtc/advanced-features/advanced-beauty':
    '/zh-CN/realtime-media/rtc/build/video/advanced-beauty',
  'realtime-media/rtc/advanced-features/advanced-beauty-460':
    '/zh-CN/realtime-media/rtc/build/video/advanced-beauty-460',
  'realtime-media/rtc/advanced-features/advanced-beauty-legacy':
    '/zh-CN/realtime-media/rtc/build/video/advanced-beauty-legacy',
  'realtime-media/rtc/advanced-features/audio-effect-mixing':
    '/zh-CN/realtime-media/rtc/build/audio/audio-effect-mixing',
  'realtime-media/rtc/advanced-features/audio-route':
    '/zh-CN/realtime-media/rtc/build/audio/audio-route',
  'realtime-media/rtc/advanced-features/audio-stream-filter':
    '/zh-CN/realtime-media/rtc/build/audio/audio-stream-filter',
  'realtime-media/rtc/advanced-features/channel-encryption':
    '/zh-CN/realtime-media/rtc/build/channel-and-connection/channel-encryption',
  'realtime-media/rtc/advanced-features/content-inspect':
    '/zh-CN/realtime-media/rtc/build/video/content-inspect',
  'realtime-media/rtc/advanced-features/custom-audio-source':
    '/zh-CN/realtime-media/rtc/build/audio/custom-audio-source',
  'realtime-media/rtc/advanced-features/custom-video-rendering':
    '/zh-CN/realtime-media/rtc/build/video/custom-video-rendering',
  'realtime-media/rtc/advanced-features/custom-video-source':
    '/zh-CN/realtime-media/rtc/build/video/custom-video-source',
  'realtime-media/rtc/advanced-features/e2e-encryption':
    '/zh-CN/realtime-media/rtc/build/security-and-auth/e2e-encryption',
  'realtime-media/rtc/advanced-features/extensions/image-enhancement':
    '/zh-CN/realtime-media/rtc/build/extensions/image-enhancement',
  'realtime-media/rtc/advanced-features/extensions/noise-reduction':
    '/zh-CN/realtime-media/rtc/build/extensions/noise-reduction',
  'realtime-media/rtc/advanced-features/extensions/overview':
    '/zh-CN/realtime-media/rtc/build/extensions/overview',
  'realtime-media/rtc/advanced-features/extensions/release':
    '/zh-CN/realtime-media/rtc/build/extensions/release',
  'realtime-media/rtc/advanced-features/extensions/super-clarity':
    '/zh-CN/realtime-media/rtc/build/extensions/super-clarity',
  'realtime-media/rtc/advanced-features/extensions/video-compositing':
    '/zh-CN/realtime-media/rtc/build/extensions/video-compositing',
  'realtime-media/rtc/advanced-features/extensions/virtual-background':
    '/zh-CN/realtime-media/rtc/build/extensions/virtual-background',
  'realtime-media/rtc/advanced-features/extensions/voice-activity-detection':
    '/zh-CN/realtime-media/rtc/build/extensions/voice-activity-detection',
  'realtime-media/rtc/advanced-features/extensions/watermark':
    '/zh-CN/realtime-media/rtc/build/extensions/watermark',
  'realtime-media/rtc/advanced-features/face-capture':
    '/zh-CN/realtime-media/rtc/build/video/face-capture',
  'realtime-media/rtc/advanced-features/in-call-quality':
    '/zh-CN/realtime-media/rtc/build/quality-and-operations/in-call-quality',
  'realtime-media/rtc/advanced-features/media-fallback':
    '/zh-CN/realtime-media/rtc/build/quality-and-operations/media-fallback',
  'realtime-media/rtc/advanced-features/media-player':
    '/zh-CN/realtime-media/rtc/build/audio/media-player',
  'realtime-media/rtc/advanced-features/media-relay':
    '/zh-CN/realtime-media/rtc/build/channel-and-connection/media-relay',
  'realtime-media/rtc/advanced-features/multipath':
    '/zh-CN/realtime-media/rtc/build/implement-core-features/multipath',
  'realtime-media/rtc/advanced-features/multiple-channel':
    '/zh-CN/realtime-media/rtc/build/channel-and-connection/multiple-channel',
  'realtime-media/rtc/advanced-features/optimization-mode':
    '/zh-CN/realtime-media/rtc/build/quality-and-operations/optimization-mode',
  'realtime-media/rtc/advanced-features/picture-in-picture':
    '/zh-CN/realtime-media/rtc/build/video/picture-in-picture',
  'realtime-media/rtc/advanced-features/raw-audio-data':
    '/zh-CN/realtime-media/rtc/build/audio/raw-audio-data',
  'realtime-media/rtc/advanced-features/raw-video-data':
    '/zh-CN/realtime-media/rtc/build/video/raw-video-data',
  'realtime-media/rtc/advanced-features/region':
    '/zh-CN/realtime-media/rtc/build/security-and-auth/region',
  'realtime-media/rtc/advanced-features/simulcast':
    '/zh-CN/realtime-media/rtc/build/video/simulcast',
  'realtime-media/rtc/advanced-features/spatial-audio':
    '/zh-CN/realtime-media/rtc/build/audio/spatial-audio',
  'realtime-media/rtc/advanced-features/token-server-upgrade':
    '/zh-CN/realtime-media/rtc/build/security-and-auth/token-server-upgrade',
  'realtime-media/rtc/advanced-features/use-extension':
    '/zh-CN/realtime-media/rtc/build/implement-core-features/use-extension',
  'realtime-media/rtc/advanced-features/video-processing':
    '/zh-CN/realtime-media/rtc/build/video/video-processing',
  'realtime-media/rtc/advanced-features/voice-changer':
    '/zh-CN/realtime-media/rtc/build/audio/voice-changer',
  'realtime-media/rtc/basic-features/audio-profile':
    '/zh-CN/realtime-media/rtc/build/audio/audio-profile',
  'realtime-media/rtc/basic-features/audio-quick-start':
    '/zh-CN/realtime-media/rtc/build/audio/audio-quick-start',
  'realtime-media/rtc/basic-features/channel-connection':
    '/zh-CN/realtime-media/rtc/build/channel-and-connection/channel-connection',
  'realtime-media/rtc/basic-features/create-track':
    '/zh-CN/realtime-media/rtc/build/implement-core-features/create-track',
  'realtime-media/rtc/basic-features/firewall':
    '/zh-CN/realtime-media/rtc/build/security-and-auth/firewall',
  'realtime-media/rtc/basic-features/join-leave-channel':
    '/zh-CN/realtime-media/rtc/build/channel-and-connection/join-leave-channel',
  'realtime-media/rtc/basic-features/lastmile-quality':
    '/zh-CN/realtime-media/rtc/build/quality-and-operations/lastmile-quality',
  'realtime-media/rtc/basic-features/ls-quick-start':
    '/zh-CN/realtime-media/rtc/build/implement-core-features/ls-quick-start',
  'realtime-media/rtc/basic-features/publish-subscribe':
    '/zh-CN/realtime-media/rtc/build/channel-and-connection/publish-subscribe',
  'realtime-media/rtc/basic-features/screen-share':
    '/zh-CN/realtime-media/rtc/build/video/screen-share',
  'realtime-media/rtc/basic-features/switch-device':
    '/zh-CN/realtime-media/rtc/build/implement-core-features/switch-device',
  'realtime-media/rtc/basic-features/token-authentication':
    '/zh-CN/realtime-media/rtc/build/security-and-auth/token-authentication',
  'realtime-media/rtc/basic-features/tree-shaking':
    '/zh-CN/realtime-media/rtc/build/implement-core-features/tree-shaking',
  'realtime-media/rtc/basic-features/video-profile':
    '/zh-CN/realtime-media/rtc/build/video/video-profile',
  'realtime-media/rtc/basic-features/volume':
    '/zh-CN/realtime-media/rtc/build/audio/volume',
  'realtime-media/rtc/best-practice/after-migrate':
    '/zh-CN/realtime-media/rtc/reference/after-migrate',
  'realtime-media/rtc/best-practice/alpha-effect':
    '/zh-CN/realtime-media/rtc/build/video/alpha-effect',
  'realtime-media/rtc/best-practice/autoplay':
    '/zh-CN/realtime-media/rtc/build/quality-and-operations/autoplay',
  'realtime-media/rtc/best-practice/custom-layout':
    '/zh-CN/realtime-media/rtc/build/video/custom-layout',
  'realtime-media/rtc/best-practice/first-frame-rendering':
    '/zh-CN/realtime-media/rtc/build/video/first-frame-rendering',
  'realtime-media/rtc/best-practice/multi-user-video':
    '/zh-CN/realtime-media/rtc/build/video/multi-user-video',
  'realtime-media/rtc/best-practice/online-user-status':
    '/zh-CN/realtime-media/rtc/build/quality-and-operations/online-user-status',
  'realtime-media/rtc/best-practice/optimal-audio-quality':
    '/zh-CN/realtime-media/rtc/build/audio/optimal-audio-quality',
  'realtime-media/rtc/best-practice/playing-url':
    '/zh-CN/realtime-media/rtc/build/optimize-and-operate/playing-url',
  'realtime-media/rtc/best-practice/preload':
    '/zh-CN/realtime-media/rtc/build/quality-and-operations/preload',
  'realtime-media/rtc/best-practice/prevent-stream-bombing':
    '/zh-CN/realtime-media/rtc/build/security-and-auth/prevent-stream-bombing',
  'realtime-media/rtc/best-practice/reduce-app-size':
    '/zh-CN/realtime-media/rtc/build/quality-and-operations/reduce-app-size',
  'realtime-media/rtc/best-practice/rest-availability':
    '/zh-CN/realtime-media/rtc/build/quality-and-operations/rest-availability',
  'realtime-media/rtc/best-practice/user-privilege':
    '/zh-CN/realtime-media/rtc/build/security-and-auth/user-privilege',
  'realtime-media/rtc/best-practice/wildcard-token':
    '/zh-CN/realtime-media/rtc/build/security-and-auth/wildcard-token',
  'realtime-media/rtc/billing/billing-faq':
    '/zh-CN/realtime-media/rtc/reference/billing-faq',
  'realtime-media/rtc/billing/billing-strategy':
    '/zh-CN/realtime-media/rtc/reference/billing-strategy',
  'realtime-media/rtc/billing/old/billing-faq-old':
    '/zh-CN/realtime-media/rtc/reference/legacy-billing/billing-faq-old',
  'realtime-media/rtc/billing/old/billing-samples-old':
    '/zh-CN/realtime-media/rtc/reference/legacy-billing/billing-samples-old',
  'realtime-media/rtc/billing/old/billing-strategy-old':
    '/zh-CN/realtime-media/rtc/reference/legacy-billing/billing-strategy-old',
  'realtime-media/rtc/billing/old/payment-old':
    '/zh-CN/realtime-media/rtc/reference/legacy-billing/payment-old',
  'realtime-media/rtc/reference/billing-faq-old':
    '/zh-CN/realtime-media/rtc/reference/legacy-billing/billing-faq-old',
  'realtime-media/rtc/reference/billing-samples-old':
    '/zh-CN/realtime-media/rtc/reference/legacy-billing/billing-samples-old',
  'realtime-media/rtc/reference/billing-strategy-old':
    '/zh-CN/realtime-media/rtc/reference/legacy-billing/billing-strategy-old',
  'realtime-media/rtc/reference/payment-old':
    '/zh-CN/realtime-media/rtc/reference/legacy-billing/payment-old',
  'realtime-media/rtc/billing/payment':
    '/zh-CN/realtime-media/rtc/reference/payment',
  'realtime-media/rtc/error-code':
    '/zh-CN/realtime-media/rtc/reference/error-code',
  'realtime-media/rtc/experimental-features/high-quality-video':
    '/zh-CN/realtime-media/rtc/build/video/experimental-features/high-quality-video',
  'realtime-media/rtc/get-started/call-api':
    '/zh-CN/realtime-media/rtc/build/setup-and-access/call-api',
  'realtime-media/rtc/get-started/enable-service':
    '/zh-CN/realtime-media/rtc/build/setup-and-access/enable-service',
  'realtime-media/rtc/overview/billing':
    '/zh-CN/realtime-media/rtc/reference/billing',
  'realtime-media/rtc/overview/browser-compatibility':
    '/zh-CN/realtime-media/rtc/reference/browser-compatibility',
  'realtime-media/rtc/overview/key-concept':
    '/zh-CN/realtime-media/rtc/reference/key-concept',
  'realtime-media/rtc/overview/key-concept.csharp':
    '/zh-CN/realtime-media/rtc/reference/key-concept?platform=csharp',
  'realtime-media/rtc/overview/migration-guide':
    '/zh-CN/realtime-media/rtc/reference/migration-guide',
  'realtime-media/rtc/overview/product-overview': '/zh-CN/realtime-media/rtc',
  'realtime-media/rtc/overview/release-notes':
    '/zh-CN/realtime-media/rtc/reference/release-notes',
  'realtime-media/rtc/overview/sunset-plan':
    '/zh-CN/realtime-media/rtc/reference/sunset-plan',
  'realtime-media/rtc/quota': '/zh-CN/realtime-media/rtc/reference/quota',
  'realtime-media/rtc/resources':
    '/zh-CN/realtime-media/rtc/reference/downloads',
  'realtime-media/rtc/response-code':
    '/zh-CN/realtime-media/rtc/reference/response-code',
  'realtime-media/rtc/user-guides/channel-management':
    '/zh-CN/realtime-media/rtc/build/security-and-auth/channel-management',
  'realtime-media/rtc/user-guides/http-basic-auth':
    '/zh-CN/realtime-media/rtc/build/security-and-auth/http-basic-auth',
  'realtime-media/rtc/webhook/events':
    '/zh-CN/realtime-media/rtc/reference/events',
  'realtime-media/rtc/webhook/receive_webhook':
    '/zh-CN/realtime-media/rtc/build/monitor-events/receive_webhook',
  'realtime-media/rtm/error-codes':
    '/zh-CN/realtime-media/rtm/build/troubleshooting',
  'realtime-media/rtm/get-started/enable-service':
    '/zh-CN/realtime-media/rtm/build/setup-and-access/enable-service',
  'realtime-media/rtm/overview/billing/billing-rules':
    '/zh-CN/realtime-media/rtm/reference/billing/billing-rules',
  'realtime-media/rtm/overview/billing/billing-strategy':
    '/zh-CN/realtime-media/rtm/reference/billing/billing-strategy',
  'realtime-media/rtm/overview/feature-list':
    '/zh-CN/realtime-media/rtm/reference/feature-list',
  'realtime-media/rtm/overview/migration-guide':
    '/zh-CN/realtime-media/rtm/reference/migration-guide',
  'realtime-media/rtm/overview/platform-support':
    '/zh-CN/realtime-media/rtm/reference/platform-support',
  'realtime-media/rtm/overview/release-notes':
    '/zh-CN/realtime-media/rtm/reference/release-notes',
  'realtime-media/rtm/resources':
    '/zh-CN/realtime-media/rtm/reference/downloads',
  'realtime-media/rtm/reference/error-codes':
    '/zh-CN/realtime-media/rtm/build/troubleshooting',
  'realtime-media/rtm/reference/link-state':
    '/zh-CN/realtime-media/rtm/build/manage-connections/link-state',
  'realtime-media/rtm/reference/metadata-events':
    '/zh-CN/realtime-media/rtm/build/manage-metadata/metadata-events',
  'realtime-media/rtm/reference/presence-events':
    '/zh-CN/realtime-media/rtm/build/manage-presence/presence-events',
  'realtime-media/rtm/reference/topic-events':
    '/zh-CN/realtime-media/rtm/build/manage-topics/topic-events',
  'realtime-media/rtm/security':
    '/zh-CN/introduction/security/sdk-compliance/rtm-sdk',
  'realtime-media/rtm/sunset-policy':
    '/zh-CN/realtime-media/rtm/reference/sunset-policy',
  'realtime-media/rtm/user-guide/channel/channel-basic':
    '/zh-CN/realtime-media/rtm/build/manage-channels/channel-basic',
  'realtime-media/rtm/user-guide/channel/channel-name':
    '/zh-CN/realtime-media/rtm/build/manage-channels/channel-name',
  'realtime-media/rtm/user-guide/channel/message-channel':
    '/zh-CN/realtime-media/rtm/build/manage-channels/message-channel',
  'realtime-media/rtm/user-guide/channel/stream-channel':
    '/zh-CN/realtime-media/rtm/build/manage-channels/stream-channel',
  'realtime-media/rtm/user-guide/link/link-basic':
    '/zh-CN/realtime-media/rtm/build/manage-connections/link-basic',
  'realtime-media/rtm/user-guide/link/link-state':
    '/zh-CN/realtime-media/rtm/build/manage-connections/link-state',
  'realtime-media/rtm/user-guide/message/add-event-listener':
    '/zh-CN/realtime-media/rtm/build/manage-messages/add-event-listener',
  'realtime-media/rtm/user-guide/message/constructed':
    '/zh-CN/realtime-media/rtm/build/manage-messages/constructed',
  'realtime-media/rtm/user-guide/message/history-message':
    '/zh-CN/realtime-media/rtm/build/manage-messages/history-message',
  'realtime-media/rtm/user-guide/message/send-message':
    '/zh-CN/realtime-media/rtm/build/manage-messages/send-message',
  'realtime-media/rtm/user-guide/message/serialized':
    '/zh-CN/realtime-media/rtm/build/manage-messages/serialized',
  'realtime-media/rtm/user-guide/presence/event':
    '/zh-CN/realtime-media/rtm/build/manage-presence/presence-events',
  'realtime-media/rtm/user-guide/presence/presence-basic':
    '/zh-CN/realtime-media/rtm/build/manage-presence/presence-basic',
  'realtime-media/rtm/user-guide/presence/temporary-user-state':
    '/zh-CN/realtime-media/rtm/build/manage-presence/temporary-user-state',
  'realtime-media/rtm/user-guide/setup/account-and-billing':
    '/zh-CN/realtime-media/rtm/reference/account-and-billing',
  'realtime-media/rtm/user-guide/setup/api-limits':
    '/zh-CN/realtime-media/rtm/reference/api-limits',
  'realtime-media/rtm/user-guide/setup/application-setup':
    '/zh-CN/realtime-media/rtm/build/setup-and-access/application-setup',
  'realtime-media/rtm/user-guide/setup/data-security':
    '/zh-CN/realtime-media/rtm/reference/data-security',
  'realtime-media/rtm/user-guide/setup/data-storage':
    '/zh-CN/realtime-media/rtm/build/setup-and-access/data-storage',
  'realtime-media/rtm/user-guide/setup/login':
    '/zh-CN/realtime-media/rtm/build/setup-and-access/login',
  'realtime-media/rtm/user-guide/setup/private-setup':
    '/zh-CN/realtime-media/rtm/build/setup-and-access/private-setup',
  'realtime-media/rtm/user-guide/storage/channel-metadata':
    '/zh-CN/realtime-media/rtm/build/manage-metadata/channel-metadata',
  'realtime-media/rtm/user-guide/storage/event':
    '/zh-CN/realtime-media/rtm/build/manage-metadata/metadata-events',
  'realtime-media/rtm/user-guide/storage/user-metadata':
    '/zh-CN/realtime-media/rtm/build/manage-metadata/user-metadata',
  'realtime-media/rtm/user-guide/token/token-generation':
    '/zh-CN/realtime-media/rtm/build/security-and-auth/token-generation',
  'realtime-media/rtm/user-guide/token/user-authentication':
    '/zh-CN/realtime-media/rtm/build/security-and-auth/user-authentication',
  'realtime-media/rtm/user-guide/topic/event':
    '/zh-CN/realtime-media/rtm/build/manage-topics/topic-events',
  'realtime-media/rtm/user-guide/topic/topic-basic':
    '/zh-CN/realtime-media/rtm/build/manage-topics/topic-basic',
  'realtime-media/rtm/user-guide/topic/usage':
    '/zh-CN/realtime-media/rtm/build/manage-topics/usage',
  'realtime-media/rtmp-gateway/api/video-profile':
    '/zh-CN/realtime-media/rtmp-gateway/reference/video-profile',
  'realtime-media/rtmp-gateway/best-practices/checklist':
    '/zh-CN/realtime-media/rtmp-gateway/build/optimize-and-operate/checklist',
  'realtime-media/rtmp-gateway/best-practices/rest-availability':
    '/zh-CN/realtime-media/rtmp-gateway/build/optimize-and-operate/rest-availability',
  'realtime-media/rtmp-gateway/best-practices/rtmp-domain-switch':
    '/zh-CN/realtime-media/rtmp-gateway/build/manage-media-streams/rtmp-domain-switch',
  'realtime-media/rtmp-gateway/get-started/call-api':
    '/zh-CN/realtime-media/rtmp-gateway/build/setup-and-access/call-api',
  'realtime-media/rtmp-gateway/get-started/enable-service':
    '/zh-CN/realtime-media/rtmp-gateway/build/setup-and-access/enable-service',
  'realtime-media/rtmp-gateway/overview/billing':
    '/zh-CN/realtime-media/rtmp-gateway/reference/billing',
  'realtime-media/rtmp-gateway/overview/payment':
    '/zh-CN/realtime-media/rtmp-gateway/reference/payment',
  'realtime-media/rtmp-gateway/overview/product-overview':
    '/zh-CN/realtime-media/rtmp-gateway',
  'realtime-media/rtmp-gateway/quota':
    '/zh-CN/realtime-media/rtmp-gateway/reference/quota',
  'realtime-media/rtmp-gateway/response-code':
    '/zh-CN/realtime-media/rtmp-gateway/reference/response-code',
  'realtime-media/rtmp-gateway/user-guides/http-auth':
    '/zh-CN/realtime-media/rtmp-gateway/build/setup-and-access/http-auth',
  'realtime-media/rtmp-gateway/webhook/enable-ncs':
    '/zh-CN/realtime-media/rtmp-gateway/build/monitor-events/enable-ncs',
  'realtime-media/rtmp-gateway/webhook/ncs-events':
    '/zh-CN/realtime-media/rtmp-gateway/reference/ncs-events',
  'realtime-media/rtsa/advanced-features/data-stream':
    '/zh-CN/realtime-media/rtsa/build/implement-core-features/data-stream',
  'realtime-media/rtsa/advanced-features/encryption':
    '/zh-CN/realtime-media/rtsa/build/implement-core-features/encryption',
  'realtime-media/rtsa/advanced-features/multi-channel':
    '/zh-CN/realtime-media/rtsa/build/implement-core-features/multi-channel',
  'realtime-media/rtsa/advanced-features/region-limit':
    '/zh-CN/realtime-media/rtsa/build/setup-and-access/region-limit',
  'realtime-media/rtsa/advanced-features/send-message-through-rdt-channel':
    '/zh-CN/realtime-media/rtsa/build/implement-core-features/send-message-through-rdt-channel',
  'realtime-media/rtsa/advanced-features/string-uid':
    '/zh-CN/realtime-media/rtsa/build/implement-core-features/string-uid',
  'realtime-media/rtsa/basic-features/audio-codec':
    '/zh-CN/realtime-media/rtsa/build/implement-core-features/audio-codec',
  'realtime-media/rtsa/basic-features/bitrate-adaption':
    '/zh-CN/realtime-media/rtsa/build/implement-core-features/bitrate-adaption',
  'realtime-media/rtsa/basic-features/cloud-proxy':
    '/zh-CN/realtime-media/rtsa/build/setup-and-access/cloud-proxy',
  'realtime-media/rtsa/basic-features/key-frame':
    '/zh-CN/realtime-media/rtsa/build/implement-core-features/key-frame',
  'realtime-media/rtsa/basic-features/license':
    '/zh-CN/realtime-media/rtsa/build/setup-and-access/license',
  'realtime-media/rtsa/basic-features/stream-state':
    '/zh-CN/realtime-media/rtsa/build/implement-core-features/stream-state',
  'realtime-media/rtsa/best-practices/interoperate-rtc':
    '/zh-CN/realtime-media/rtsa/build/optimize-and-operate/interoperate-rtc',
  'realtime-media/rtsa/error-codes':
    '/zh-CN/realtime-media/rtsa/reference/error-codes',
  'realtime-media/rtsa/get-started/enable-service':
    '/zh-CN/realtime-media/rtsa/build/setup-and-access/enable-service',
  'realtime-media/rtsa/get-started/implement-transmission':
    '/zh-CN/realtime-media/rtsa/build/implement-core-features/implement-transmission',
  'realtime-media/rtsa/overview/billing':
    '/zh-CN/realtime-media/rtsa/reference/billing',
  'realtime-media/rtsa/overview/product-overview': '/zh-CN/realtime-media/rtsa',
  'realtime-media/rtsa/overview/release-notes':
    '/zh-CN/realtime-media/rtsa/reference/release-notes',
  'realtime-media/rtsa/overview/sunset':
    '/zh-CN/realtime-media/rtsa/reference/sunset',
  'realtime-media/rtsa/resources':
    '/zh-CN/realtime-media/rtsa/reference/downloads',
  'realtime-media/sdk-extensions/metakit/api-ref':
    '/zh-CN/realtime-media/sdk-extensions/metakit/reference/api-ref',
  'realtime-media/sdk-extensions/metakit/dress':
    '/zh-CN/realtime-media/sdk-extensions/metakit/build/implement-core-features/dress',
  'realtime-media/sdk-extensions/metakit/face':
    '/zh-CN/realtime-media/sdk-extensions/metakit/build/implement-core-features/face',
  'realtime-media/sdk-extensions/metakit/overview':
    '/zh-CN/realtime-media/sdk-extensions/metakit',
  'realtime-media/sdk-extensions/metakit/quick-start':
    '/zh-CN/realtime-media/sdk-extensions/metakit/build/implement-core-features/quick-start',
  'realtime-media/sdk-extensions/metakit/release-notes':
    '/zh-CN/realtime-media/sdk-extensions/metakit/reference/release-notes',
  'realtime-media/sdk-extensions/metakit/resources':
    '/zh-CN/realtime-media/sdk-extensions/metakit/reference/downloads',
  'realtime-media/sdk-extensions/portrait-rhythm/key-value':
    '/zh-CN/realtime-media/sdk-extensions/portrait-rhythm/build/implement-core-features/key-value',
  'realtime-media/sdk-extensions/portrait-rhythm/overview':
    '/zh-CN/realtime-media/sdk-extensions/portrait-rhythm',
  'realtime-media/sdk-extensions/portrait-rhythm/quick-start':
    '/zh-CN/realtime-media/sdk-extensions/portrait-rhythm/build/implement-core-features/quick-start',
  'realtime-media/sdk-extensions/portrait-rhythm/release-notes':
    '/zh-CN/realtime-media/sdk-extensions/portrait-rhythm/reference/release-notes',
  'realtime-media/sdk-extensions/portrait-rhythm/resources':
    '/zh-CN/realtime-media/sdk-extensions/portrait-rhythm/reference/downloads',
  'realtime-media/transcoding/api/video-profile':
    '/zh-CN/realtime-media/transcoding/reference/video-profile',
  'realtime-media/transcoding/best-practices/check-service':
    '/zh-CN/realtime-media/transcoding/build/optimize-and-operate/check-service',
  'realtime-media/transcoding/best-practices/rest-availability':
    '/zh-CN/realtime-media/transcoding/build/optimize-and-operate/rest-availability',
  'realtime-media/transcoding/get-started/call-api':
    '/zh-CN/realtime-media/transcoding/build/setup-and-access/call-api',
  'realtime-media/transcoding/get-started/enable-service':
    '/zh-CN/realtime-media/transcoding/build/setup-and-access/enable-service',
  'realtime-media/transcoding/overview/billing':
    '/zh-CN/realtime-media/transcoding/reference/billing',
  'realtime-media/transcoding/overview/product-overview':
    '/zh-CN/realtime-media/transcoding',
  'realtime-media/transcoding/quota':
    '/zh-CN/realtime-media/transcoding/reference/quota',
  'realtime-media/transcoding/response-code':
    '/zh-CN/realtime-media/transcoding/reference/response-code',
  'realtime-media/transcoding/user-guides/enable-multiple-bitrate':
    '/zh-CN/realtime-media/transcoding/build/setup-and-access/enable-multiple-bitrate',
  'realtime-media/transcoding/user-guides/http-auth':
    '/zh-CN/realtime-media/transcoding/build/setup-and-access/http-auth',
  'realtime-media/transcoding/webhook/enable-event-notification':
    '/zh-CN/realtime-media/transcoding/build/monitor-events/enable-event-notification',
  'realtime-media/transcoding/webhook/ncs-events':
    '/zh-CN/api-reference/api-ref/cloud-transcoding/ncs-events',
  'realtime-media/transcoding/reference/ncs-events':
    '/zh-CN/api-reference/api-ref/cloud-transcoding/ncs-events',
  'realtime-media/usage-analytics/fls/data':
    '/zh-CN/realtime-media/usage-analytics/build/fls/data',
  'realtime-media/usage-analytics/overview/billing':
    '/zh-CN/realtime-media/usage-analytics/reference/billing',
  'realtime-media/usage-analytics/overview/product-overview':
    '/zh-CN/realtime-media/usage-analytics',
  'realtime-media/usage-analytics/overview/release-notes':
    '/zh-CN/realtime-media/usage-analytics/reference/release-notes',
  'realtime-media/usage-analytics/rtc/alarm':
    '/zh-CN/realtime-media/usage-analytics/build/rtc/alarm',
  'realtime-media/usage-analytics/rtc/api-limits':
    '/zh-CN/realtime-media/usage-analytics/reference/api-limits',
  'realtime-media/usage-analytics/rtc/call-search/call-detail':
    '/zh-CN/realtime-media/usage-analytics/build/rtc/call-search/call-detail',
  'realtime-media/usage-analytics/rtc/call-search/concept':
    '/zh-CN/realtime-media/usage-analytics/reference/concept',
  'realtime-media/usage-analytics/rtc/call-search/overview':
    '/zh-CN/realtime-media/usage-analytics/build/rtc/call-search/overview',
  'realtime-media/usage-analytics/rtc/call-search/troubleshooting':
    '/zh-CN/realtime-media/usage-analytics/build/rtc/call-search/troubleshooting',
  'realtime-media/usage-analytics/rtc/data-insight/basic':
    '/zh-CN/realtime-media/usage-analytics/build/rtc/data-insight/basic',
  'realtime-media/usage-analytics/rtc/data-insight/plus':
    '/zh-CN/realtime-media/usage-analytics/build/rtc/data-insight/plus',
  'realtime-media/usage-analytics/rtc/data-insight/troubleshooting':
    '/zh-CN/realtime-media/usage-analytics/build/rtc/data-insight/troubleshooting',
  'realtime-media/usage-analytics/rtc/embeded':
    '/zh-CN/realtime-media/usage-analytics/build/rtc/embeded',
  'realtime-media/usage-analytics/rtc/guarantee-rest':
    '/zh-CN/realtime-media/usage-analytics/build/rtc/guarantee-rest',
  'realtime-media/usage-analytics/rtc/metric-ids':
    '/zh-CN/realtime-media/usage-analytics/build/rtc/metric-ids',
  'realtime-media/usage-analytics/rtc/monitor':
    '/zh-CN/realtime-media/usage-analytics/build/rtc/monitor',
  'realtime-media/usage-analytics/rtc/response-code':
    '/zh-CN/realtime-media/usage-analytics/reference/response-code',
  'realtime-media/usage-analytics/rtm/concept':
    '/zh-CN/realtime-media/usage-analytics/reference/concept-rtm',
  'realtime-media/usage-analytics/rtm/data-insight':
    '/zh-CN/realtime-media/usage-analytics/build/rtm/data-insight',
  'realtime-media/whiteboard/fastboard-sdk/advanced-features/convert-files':
    '/zh-CN/realtime-media/whiteboard/fastboard-sdk/build/extend-whiteboard/convert-files',
  'realtime-media/whiteboard/fastboard-sdk/advanced-features/customize-widget':
    '/zh-CN/realtime-media/whiteboard/fastboard-sdk/build/manage-whiteboard/customize-widget',
  'realtime-media/whiteboard/fastboard-sdk/advanced-features/record-and-replay':
    '/zh-CN/realtime-media/whiteboard/fastboard-sdk/build/extend-whiteboard/record-and-replay',
  'realtime-media/whiteboard/fastboard-sdk/basic-features/generate-token':
    '/zh-CN/realtime-media/whiteboard/fastboard-sdk/build/setup-and-access/generate-token',
  'realtime-media/whiteboard/fastboard-sdk/basic-features/present-files-fb':
    '/zh-CN/realtime-media/whiteboard/fastboard-sdk/build/manage-whiteboard/present-files-fb',
  'realtime-media/whiteboard/fastboard-sdk/conversion-webhook':
    '/zh-CN/realtime-media/whiteboard/fastboard-sdk/build/extend-whiteboard/conversion-webhook',
  'realtime-media/whiteboard/fastboard-sdk/get-started/call-api':
    '/zh-CN/realtime-media/whiteboard/fastboard-sdk/build/setup-and-access/call-api',
  'realtime-media/whiteboard/fastboard-sdk/get-started':
    '/zh-CN/realtime-media/whiteboard/fastboard-sdk/get-started/join-room-fb',
  'realtime-media/whiteboard/fastboard-sdk/get-started/enable-service':
    '/zh-CN/realtime-media/whiteboard/fastboard-sdk/build/setup-and-access/enable-service',
  'realtime-media/whiteboard/fastboard-sdk/get-started/migrate-from-netless':
    '/zh-CN/realtime-media/whiteboard/fastboard-sdk/reference/migrate-from-netless',
  'realtime-media/whiteboard/fastboard-sdk/overview/billing':
    '/zh-CN/realtime-media/whiteboard/fastboard-sdk/reference/billing',
  'realtime-media/whiteboard/fastboard-sdk/overview/concepts':
    '/zh-CN/realtime-media/whiteboard/reference/concepts',
  'realtime-media/whiteboard/fastboard-sdk/overview/convert-ppt':
    '/zh-CN/realtime-media/whiteboard/fastboard-sdk/reference/convert-ppt',
  'realtime-media/whiteboard/fastboard-sdk/overview/product-overview':
    '/zh-CN/realtime-media/whiteboard/fastboard-sdk',
  'realtime-media/whiteboard/fastboard-sdk/overview/qps-pricing':
    '/zh-CN/realtime-media/whiteboard/fastboard-sdk/reference/qps-pricing',
  'realtime-media/whiteboard/fastboard-sdk/release-notes-fb':
    '/zh-CN/realtime-media/whiteboard/fastboard-sdk/reference/release-notes-fb',
  'realtime-media/whiteboard/fastboard-sdk/resources-fb':
    '/zh-CN/realtime-media/whiteboard/fastboard-sdk/reference/downloads',
  'realtime-media/whiteboard/fastboard-sdk/response-code':
    '/zh-CN/realtime-media/whiteboard/fastboard-sdk/reference/response-code',
  'realtime-media/whiteboard/fastboard-sdk/solution-compare':
    '/zh-CN/realtime-media/whiteboard#如何选择互动白板-sdk-和-fastboard-sdk',
  'realtime-media/whiteboard/reference':
    '/zh-CN/realtime-media/whiteboard/reference/concepts',
  'realtime-media/whiteboard/whiteboard-sdk/advanced-features/convert-files':
    '/zh-CN/realtime-media/whiteboard/whiteboard-sdk/build/extend-whiteboard/convert-files',
  'realtime-media/whiteboard/whiteboard-sdk/advanced-features/custom-event':
    '/zh-CN/realtime-media/whiteboard/whiteboard-sdk/build/extend-whiteboard/custom-event',
  'realtime-media/whiteboard/whiteboard-sdk/advanced-features/record-and-replay':
    '/zh-CN/realtime-media/whiteboard/whiteboard-sdk/build/extend-whiteboard/record-and-replay',
  'realtime-media/whiteboard/whiteboard-sdk/basic-features/firewall':
    '/zh-CN/realtime-media/whiteboard/whiteboard-sdk/build/setup-and-access/firewall',
  'realtime-media/whiteboard/whiteboard-sdk/basic-features/generate-token':
    '/zh-CN/realtime-media/whiteboard/whiteboard-sdk/build/setup-and-access/generate-token',
  'realtime-media/whiteboard/whiteboard-sdk/basic-features/manage-room-phase':
    '/zh-CN/realtime-media/whiteboard/whiteboard-sdk/build/manage-whiteboard/manage-room-phase',
  'realtime-media/whiteboard/whiteboard-sdk/basic-features/manage-room-status':
    '/zh-CN/realtime-media/whiteboard/whiteboard-sdk/build/manage-whiteboard/manage-room-status',
  'realtime-media/whiteboard/whiteboard-sdk/basic-features/manage-scene':
    '/zh-CN/realtime-media/whiteboard/whiteboard-sdk/build/manage-whiteboard/manage-scene',
  'realtime-media/whiteboard/whiteboard-sdk/basic-features/present-files-wb':
    '/zh-CN/realtime-media/whiteboard/whiteboard-sdk/build/manage-whiteboard/present-files-wb',
  'realtime-media/whiteboard/whiteboard-sdk/basic-features/use-tools-wb':
    '/zh-CN/realtime-media/whiteboard/whiteboard-sdk/build/manage-whiteboard/use-tools-wb',
  'realtime-media/whiteboard/whiteboard-sdk/conversion-webhook':
    '/zh-CN/realtime-media/whiteboard/whiteboard-sdk/build/extend-whiteboard/conversion-webhook',
  'realtime-media/whiteboard/whiteboard-sdk/get-started/call-api':
    '/zh-CN/realtime-media/whiteboard/whiteboard-sdk/build/setup-and-access/call-api',
  'realtime-media/whiteboard/whiteboard-sdk/get-started':
    '/zh-CN/realtime-media/whiteboard/whiteboard-sdk/get-started/join-room-wb',
  'realtime-media/whiteboard/whiteboard-sdk/get-started/enable-service':
    '/zh-CN/realtime-media/whiteboard/whiteboard-sdk/build/setup-and-access/enable-service',
  'realtime-media/whiteboard/whiteboard-sdk/get-started/migrate-from-netless':
    '/zh-CN/realtime-media/whiteboard/whiteboard-sdk/reference/migrate-from-netless',
  'realtime-media/whiteboard/whiteboard-sdk/overview/billing':
    '/zh-CN/realtime-media/whiteboard/whiteboard-sdk/reference/billing',
  'realtime-media/whiteboard/whiteboard-sdk/overview/concepts':
    '/zh-CN/realtime-media/whiteboard/reference/concepts',
  'realtime-media/whiteboard/whiteboard-sdk/overview/convert-ppt':
    '/zh-CN/realtime-media/whiteboard/whiteboard-sdk/reference/convert-ppt',
  'realtime-media/whiteboard/whiteboard-sdk/overview/product-overview':
    '/zh-CN/realtime-media/whiteboard/whiteboard-sdk',
  'realtime-media/whiteboard/whiteboard-sdk/overview/qps-pricing':
    '/zh-CN/realtime-media/whiteboard/whiteboard-sdk/reference/qps-pricing',
  'realtime-media/whiteboard/whiteboard-sdk/release-notes-wb':
    '/zh-CN/realtime-media/whiteboard/whiteboard-sdk/reference/release-notes-wb',
  'realtime-media/whiteboard/whiteboard-sdk/resources-wb':
    '/zh-CN/realtime-media/whiteboard/whiteboard-sdk/reference/downloads',
  'realtime-media/whiteboard/whiteboard-sdk/response-code':
    '/zh-CN/realtime-media/whiteboard/whiteboard-sdk/reference/response-code',
  'realtime-media/whiteboard/whiteboard-sdk/solution-compare':
    '/zh-CN/realtime-media/whiteboard#如何选择互动白板-sdk-和-fastboard-sdk',
  'solutions/art-class/advanced-features/brightness-correction':
    '/zh-CN/solutions/art-class/build/customize-and-extend/brightness-correction',
  'solutions/art-class/advanced-features/trapezoid-correction':
    '/zh-CN/solutions/art-class/build/customize-and-extend/trapezoid-correction',
  'solutions/art-class/api/correction':
    '/zh-CN/solutions/art-class/reference/correction',
  'solutions/art-class/get-started/enable-service':
    '/zh-CN/solutions/art-class/build/setup-and-access/enable-service',
  'solutions/art-class/overview/product-overview': '/zh-CN/solutions/art-class',
  'solutions/art-class/resources':
    '/zh-CN/solutions/art-class/reference/downloads',
  'solutions/breakout-classroom/overview/product-overview':
    '/zh-CN/solutions/breakout-classroom',
  'solutions/breakout-classroom/paas/architecture':
    '/zh-CN/solutions/breakout-classroom/build/paas/architecture',
  'solutions/breakout-classroom/paas/best-practices':
    '/zh-CN/solutions/breakout-classroom/build/paas/best-practices',
  'solutions/breakout-classroom/paas/integration-guide':
    '/zh-CN/solutions/breakout-classroom/build/paas/integration-guide',
  'solutions/chatroom/sdk/api': '/zh-CN/solutions/chatroom/sdk/reference/api',
  'solutions/chatroom/sdk/api/im-api':
    '/zh-CN/solutions/chatroom/sdk/reference/im-api',
  'solutions/chatroom/sdk/api/rtc-api':
    '/zh-CN/solutions/chatroom/sdk/reference/rtc-api',
  'solutions/chatroom/sdk/get-started/enable-service':
    '/zh-CN/solutions/chatroom/sdk/build/setup-and-access/enable-service',
  'solutions/chatroom/sdk/get-started/quick-integration':
    '/zh-CN/solutions/chatroom/sdk/build/implement-core-features/quick-integration',
  'solutions/chatroom/sdk/overview': '/zh-CN/solutions/chatroom/sdk',
  'solutions/chatroom/sdk/resources':
    '/zh-CN/solutions/chatroom/sdk/reference/downloads',
  'solutions/chatroom/sdk/solution-compare':
    '/zh-CN/solutions/chatroom/sdk/reference/solution-compare',
  'solutions/chatroom/sdk/user-guides/mic-seat-management':
    '/zh-CN/solutions/chatroom/sdk/build/implement-core-features/mic-seat-management',
  'solutions/chatroom/sdk/user-guides/set-audio':
    '/zh-CN/solutions/chatroom/sdk/build/implement-core-features/set-audio',
  'solutions/chatroom/uikit/get-started/enable-service':
    '/zh-CN/solutions/chatroom/uikit/build/setup-and-access/enable-service',
  'solutions/chatroom/uikit/get-started/quick-integration':
    '/zh-CN/solutions/chatroom/uikit/build/implement-core-features/quick-integration',
  'solutions/chatroom/uikit/get-started/run-github-project':
    '/zh-CN/solutions/chatroom/uikit/build/implement-core-features/run-github-project',
  'solutions/chatroom/uikit/get-started/run-github-project-backend':
    '/zh-CN/solutions/chatroom/uikit/build/implement-core-features/run-github-project-backend',
  'solutions/chatroom/uikit/overview': '/zh-CN/solutions/chatroom/uikit',
  'solutions/chatroom/uikit/resources':
    '/zh-CN/solutions/chatroom/uikit/reference/downloads',
  'solutions/chatroom/uikit/solution-compare':
    '/zh-CN/solutions/chatroom/uikit/reference/solution-compare',
  'solutions/digital-learning/course-delivery/integration':
    '/zh-CN/solutions/digital-learning/course-delivery/build/implement-core-features/integration',
  'solutions/digital-learning/course-delivery/overview':
    '/zh-CN/solutions/digital-learning/course-delivery',
  'solutions/digital-learning/course-resource/integration':
    '/zh-CN/solutions/digital-learning/course-resource/build/implement-core-features/integration',
  'solutions/digital-learning/course-resource/overview':
    '/zh-CN/solutions/digital-learning/course-resource',
  'solutions/digital-learning/school-resource/integration':
    '/zh-CN/solutions/digital-learning/school-resource/build/implement-core-features/integration',
  'solutions/digital-learning/school-resource/overview':
    '/zh-CN/solutions/digital-learning/school-resource',
  'solutions/flexible-classroom/advanced-features/custom-ui':
    '/zh-CN/solutions/flexible-classroom/build/customize-and-extend/custom-ui',
  'solutions/flexible-classroom/advanced-features/custom-ui-new':
    '/zh-CN/solutions/flexible-classroom/build/customize-and-extend/custom-ui-new',
  'solutions/flexible-classroom/advanced-features/widget':
    '/zh-CN/solutions/flexible-classroom/build/customize-and-extend/widget',
  'solutions/flexible-classroom/advanced-features/widget-previous':
    '/zh-CN/solutions/flexible-classroom/build/customize-and-extend/widget-previous',
  'solutions/flexible-classroom/advanced-features/widget-tech':
    '/zh-CN/solutions/flexible-classroom/build/customize-and-extend/widget-tech',
  'solutions/flexible-classroom/api/api-classroom':
    '/zh-CN/api-reference/flexible-classroom/restful-api/api-classroom',
  'solutions/flexible-classroom/api/api-recording':
    '/zh-CN/api-reference/flexible-classroom/restful-api/api-recording',
  'solutions/flexible-classroom/api/api-sync':
    '/zh-CN/api-reference/flexible-classroom/restful-api/api-sync',
  'solutions/flexible-classroom/api/api-user':
    '/zh-CN/api-reference/flexible-classroom/restful-api/api-user',
  'solutions/flexible-classroom/api/api-widget':
    '/zh-CN/api-reference/flexible-classroom/restful-api/api-widget',
  'solutions/flexible-classroom/basic-features/generate-token':
    '/zh-CN/solutions/flexible-classroom/build/setup-and-access/generate-token',
  'solutions/flexible-classroom/basic-features/http-token-auth':
    '/zh-CN/solutions/flexible-classroom/build/setup-and-access/http-token-auth',
  'solutions/flexible-classroom/basic-features/proctor-online-exams':
    '/zh-CN/solutions/flexible-classroom/build/manage-classroom/proctor-online-exams',
  'solutions/flexible-classroom/basic-features/whiteboard-on-off':
    '/zh-CN/solutions/flexible-classroom/build/manage-classroom/whiteboard-on-off',
  'solutions/flexible-classroom/best-practices/classroom-properties':
    '/zh-CN/solutions/flexible-classroom/build/manage-classroom/classroom-properties',
  'solutions/flexible-classroom/best-practices/courseware':
    '/zh-CN/solutions/flexible-classroom/build/manage-classroom/courseware',
  'solutions/flexible-classroom/best-practices/high-availability':
    '/zh-CN/solutions/flexible-classroom/build/manage-classroom/high-availability',
  'solutions/flexible-classroom/best-practices/integrate-systems':
    '/zh-CN/solutions/flexible-classroom/build/manage-classroom/integrate-systems',
  'solutions/flexible-classroom/best-practices/record':
    '/zh-CN/solutions/flexible-classroom/build/manage-classroom/record',
  'solutions/flexible-classroom/get-started/call-api':
    '/zh-CN/solutions/flexible-classroom/reference/call-api',
  'solutions/flexible-classroom/get-started/configure':
    '/zh-CN/solutions/flexible-classroom/build/setup-and-access/configure',
  'solutions/flexible-classroom/get-started/enable':
    '/zh-CN/solutions/flexible-classroom/build/setup-and-access/enable',
  'solutions/flexible-classroom/overview/basic-concept':
    '/zh-CN/solutions/flexible-classroom/reference/basic-concept',
  'solutions/flexible-classroom/overview/billing':
    '/zh-CN/solutions/flexible-classroom/reference/billing',
  'solutions/flexible-classroom/overview/migration':
    '/zh-CN/solutions/flexible-classroom/reference/migration',
  'solutions/flexible-classroom/overview/platform-support':
    '/zh-CN/solutions/flexible-classroom/reference/platform-support',
  'solutions/flexible-classroom/overview/product':
    '/zh-CN/solutions/flexible-classroom',
  'solutions/flexible-classroom/overview/release-notes':
    '/zh-CN/solutions/flexible-classroom/reference/release-notes',
  'solutions/flexible-classroom/overview/tech-architect':
    '/zh-CN/solutions/flexible-classroom/reference/tech-architect',
  'solutions/flexible-classroom/quota':
    '/zh-CN/solutions/flexible-classroom/reference/quota',
  'solutions/flexible-classroom/resources':
    '/zh-CN/solutions/flexible-classroom/reference/downloads',
  'solutions/flexible-classroom/response-code':
    '/zh-CN/solutions/flexible-classroom/reference/response-code',
  'solutions/game-voice/api': '/zh-CN/solutions/game-voice/reference/api',
  'solutions/game-voice/best-practices/audio-experience-optimization':
    '/zh-CN/solutions/game-voice/build/implement-core-features/audio-experience-optimization',
  'solutions/game-voice/get-started/enable-service':
    '/zh-CN/solutions/game-voice/build/setup-and-access/enable-service',
  'solutions/game-voice/overview/billing':
    '/zh-CN/solutions/game-voice/reference/billing',
  'solutions/game-voice/overview/product-overview':
    '/zh-CN/solutions/game-voice',
  'solutions/game-voice/resources':
    '/zh-CN/solutions/game-voice/reference/downloads',
  'solutions/game-voice/user-guides/spatial-audio-sdk':
    '/zh-CN/solutions/game-voice/build/customize-and-extend/spatial-audio-sdk',
  'solutions/game-voice/user-guides/spatial-audio-wwise':
    '/zh-CN/solutions/game-voice/build/customize-and-extend/spatial-audio-wwise',
  'solutions/iot-apaas/advanced-features/alarm':
    '/zh-CN/solutions/iot-apaas/build/customize-and-extend/alarm',
  'solutions/iot-apaas/advanced-features/cloud-storage':
    '/zh-CN/solutions/iot-apaas/build/customize-and-extend/cloud-storage',
  'solutions/iot-apaas/advanced-features/upgrade-ota':
    '/zh-CN/solutions/iot-apaas/build/customize-and-extend/upgrade-ota',
  'solutions/iot-apaas/get-started/client-call':
    '/zh-CN/solutions/iot-apaas/build/implement-core-features/client-call',
  'solutions/iot-apaas/get-started/client-call-minimum':
    '/zh-CN/solutions/iot-apaas/build/implement-core-features/client-call-minimum',
  'solutions/iot-apaas/get-started/device-call':
    '/zh-CN/solutions/iot-apaas/build/implement-core-features/device-call',
  'solutions/iot-apaas/get-started/device-call-minimum':
    '/zh-CN/solutions/iot-apaas/build/implement-core-features/device-call-minimum',
  'solutions/iot-apaas/get-started/enable-service':
    '/zh-CN/solutions/iot-apaas/build/setup-and-access/enable-service',
  'solutions/iot-apaas/get-started/license':
    '/zh-CN/solutions/iot-apaas/build/setup-and-access/license',
  'solutions/iot-apaas/overview/product-overview': '/zh-CN/solutions/iot-apaas',
  'solutions/iot-apaas/overview/release-notes':
    '/zh-CN/solutions/iot-apaas/reference/release-notes',
  'solutions/iot-apaas/overview/tech-architecture':
    '/zh-CN/solutions/iot-apaas/reference/tech-architecture',
  'solutions/iot-apaas/resources':
    '/zh-CN/solutions/iot-apaas/reference/downloads',
  'solutions/iot-apaas/restful': '/zh-CN/solutions/iot-apaas/reference/restful',
  'solutions/meeting/api/create-room':
    '/zh-CN/api-reference/meeting/restful/api/create-room',
  'solutions/meeting/api/query-recording':
    '/zh-CN/api-reference/meeting/restful/api/query-recording',
  'solutions/meeting/best-practices/high-availability':
    '/zh-CN/realtime-media/meeting/build/manage-classroom/high-availability',
  'solutions/meeting/get-started/call-api':
    '/zh-CN/realtime-media/meeting/reference/call-api',
  'solutions/meeting/get-started/configure-meeting':
    '/zh-CN/realtime-media/meeting/build/manage-classroom/configure-meeting',
  'solutions/meeting/get-started/enable-service':
    '/zh-CN/realtime-media/meeting/build/setup-and-access/enable-service',
  'solutions/meeting/overview/platform-support':
    '/zh-CN/realtime-media/meeting/reference/platform-support',
  'solutions/meeting/overview/product-overview':
    '/zh-CN/realtime-media/meeting',
  'solutions/meeting/quota': '/zh-CN/realtime-media/meeting/reference/quota',
  'solutions/meeting/resources':
    '/zh-CN/realtime-media/meeting/reference/downloads',
  'solutions/meeting/response-code':
    '/zh-CN/realtime-media/meeting/reference/response-code',
  'solutions/meeting/user-guides/generate-token':
    '/zh-CN/realtime-media/meeting/build/customize-and-extend/generate-token',
  'solutions/meeting/user-guides/http-token-auth':
    '/zh-CN/realtime-media/meeting/build/customize-and-extend/http-token-auth',
  'solutions/meeting/webhook/webhook-events':
    '/zh-CN/realtime-media/meeting/reference/webhook-events',
  'solutions/meta-world/advanced-features/dress-face':
    '/zh-CN/solutions/meta-world/build/customize-and-extend/dress-face',
  'solutions/meta-world/advanced-features/share-audio-video':
    '/zh-CN/solutions/meta-world/build/customize-and-extend/share-audio-video',
  'solutions/meta-world/advanced-features/spatial-audio':
    '/zh-CN/solutions/meta-world/build/customize-and-extend/spatial-audio',
  'solutions/meta-world/api-ref/meta-api':
    '/zh-CN/solutions/meta-world/reference/meta-api',
  'solutions/meta-world/api-ref/rtc-api':
    '/zh-CN/solutions/meta-world/reference/rtc-api',
  'solutions/meta-world/basic-features/metachat':
    '/zh-CN/solutions/meta-world/build/implement-core-features/metachat',
  'solutions/meta-world/basic-features/metalive':
    '/zh-CN/solutions/meta-world/build/implement-core-features/metalive',
  'solutions/meta-world/basic-features/mixed-scenario':
    '/zh-CN/solutions/meta-world/build/implement-core-features/mixed-scenario',
  'solutions/meta-world/get-started/enable-service':
    '/zh-CN/solutions/meta-world/build/setup-and-access/enable-service',
  'solutions/meta-world/overview/demo':
    '/zh-CN/solutions/meta-world/build/implement-core-features/demo',
  'solutions/meta-world/overview/product-overview':
    '/zh-CN/solutions/meta-world',
  'solutions/meta-world/resources':
    '/zh-CN/solutions/meta-world/reference/downloads',
  'solutions/multi-usecase/non-scenario-based/karaoke':
    '/zh-CN/solutions/multi-usecase/non-scenario-based/reference/karaoke',
  'solutions/multi-usecase/non-scenario-based/overview/billing':
    '/zh-CN/solutions/multi-usecase/non-scenario-based/reference/billing',
  'solutions/multi-usecase/non-scenario-based/overview/demo':
    '/zh-CN/solutions/multi-usecase/non-scenario-based/build/implement-core-features/demo',
  'solutions/multi-usecase/non-scenario-based/overview/introduction':
    '/zh-CN/solutions/multi-usecase/non-scenario-based',
  'solutions/multi-usecase/non-scenario-based/resources':
    '/zh-CN/solutions/multi-usecase/non-scenario-based/reference/downloads',
  'solutions/multi-usecase/non-scenario-based/test':
    '/zh-CN/solutions/multi-usecase/non-scenario-based/build/implement-core-features/test',
  'solutions/multi-usecase/non-scenario-based/test2':
    '/zh-CN/solutions/multi-usecase/non-scenario-based/build/implement-core-features/test2',
  'solutions/multi-usecase/scenario-based/chorus':
    '/zh-CN/solutions/multi-usecase/scenario-based/build/implement-core-features/chorus',
  'solutions/multi-usecase/scenario-based/get-music':
    '/zh-CN/solutions/multi-usecase/scenario-based/build/implement-core-features/get-music',
  'solutions/multi-usecase/scenario-based/overview/billing':
    '/zh-CN/solutions/multi-usecase/scenario-based/reference/billing',
  'solutions/multi-usecase/scenario-based/overview/demo':
    '/zh-CN/solutions/multi-usecase/scenario-based/build/implement-core-features/demo',
  'solutions/multi-usecase/scenario-based/overview/introduction':
    '/zh-CN/solutions/multi-usecase/scenario-based',
  'solutions/multi-usecase/scenario-based/resources':
    '/zh-CN/solutions/multi-usecase/scenario-based/reference/downloads',
  'solutions/multi-usecase/scenario-based/solo':
    '/zh-CN/solutions/multi-usecase/scenario-based/build/implement-core-features/solo',
  'solutions/multi-usecase/scenario-based/test':
    '/zh-CN/solutions/multi-usecase/scenario-based/build/implement-core-features/test',
  'solutions/multi-usecase/scenario-based/test2':
    '/zh-CN/solutions/multi-usecase/scenario-based/build/implement-core-features/test2',
  'solutions/multi-usecase/ui-solution/enable-service':
    '/zh-CN/solutions/multi-usecase/ui-solution/build/setup-and-access/enable-service',
  'solutions/multi-usecase/ui-solution/kit-demo':
    '/zh-CN/solutions/multi-usecase/ui-solution/build/implement-core-features/kit-demo',
  'solutions/multi-usecase/ui-solution/overview/billing':
    '/zh-CN/solutions/multi-usecase/ui-solution/reference/billing',
  'solutions/multi-usecase/ui-solution/overview/demo':
    '/zh-CN/solutions/multi-usecase/ui-solution/build/implement-core-features/demo',
  'solutions/multi-usecase/ui-solution/overview/introduction':
    '/zh-CN/solutions/multi-usecase/ui-solution',
  'solutions/multi-usecase/ui-solution/resources':
    '/zh-CN/solutions/multi-usecase/ui-solution/reference/downloads',
  'solutions/multi-usecase/ui-solution/test':
    '/zh-CN/solutions/multi-usecase/ui-solution/build/implement-core-features/test',
  'solutions/multi-usecase/ui-solution/test2':
    '/zh-CN/solutions/multi-usecase/ui-solution/build/implement-core-features/test2',
  'solutions/multi-usecase/ui-solution/test3':
    '/zh-CN/solutions/multi-usecase/ui-solution/build/implement-core-features/test3',
  'solutions/multi-usecase/ui-solution/uikitkaraoke':
    '/zh-CN/solutions/multi-usecase/ui-solution/build/implement-core-features/uikitkaraoke',
  'solutions/one-to-one-classroom/overview/product-overview':
    '/zh-CN/solutions/one-to-one-classroom',
  'solutions/one-to-one-classroom/paas/architecture':
    '/zh-CN/solutions/one-to-one-classroom/build/paas/architecture',
  'solutions/one-to-one-classroom/paas/best-practices':
    '/zh-CN/solutions/one-to-one-classroom/build/paas/best-practices',
  'solutions/one-to-one-classroom/paas/integration-guide':
    '/zh-CN/solutions/one-to-one-classroom/build/paas/integration-guide',
  'solutions/one-to-one-live/custom-signaling/advanced-features/app-billing-policy':
    '/zh-CN/solutions/one-to-one-live/custom-signaling/reference/app-billing-policy',
  'solutions/one-to-one-live/custom-signaling/advanced-features/audio-scenario':
    '/zh-CN/solutions/one-to-one-live/custom-signaling/build/customize-and-extend/audio-scenario',
  'solutions/one-to-one-live/custom-signaling/advanced-features/integration-guideline':
    '/zh-CN/solutions/one-to-one-live/custom-signaling/build/customize-and-extend/integration-guideline',
  'solutions/one-to-one-live/custom-signaling/api/call-api':
    '/zh-CN/solutions/one-to-one-live/custom-signaling/reference/call-api',
  'solutions/one-to-one-live/custom-signaling/api/rtc-api':
    '/zh-CN/solutions/one-to-one-live/custom-signaling/reference/rtc-api',
  'solutions/one-to-one-live/custom-signaling/basic-features/implement-custom-signaling':
    '/zh-CN/solutions/one-to-one-live/custom-signaling/build/customize-and-extend/implement-custom-signaling',
  'solutions/one-to-one-live/custom-signaling/basic-features/showroom-to-one-to-one':
    '/zh-CN/solutions/one-to-one-live/custom-signaling/build/implement-core-features/showroom-to-one-to-one',
  'solutions/one-to-one-live/custom-signaling/basic-features/start-one-to-one':
    '/zh-CN/solutions/one-to-one-live/custom-signaling/build/implement-core-features/start-one-to-one',
  'solutions/one-to-one-live/custom-signaling/get-started/enable-service':
    '/zh-CN/solutions/one-to-one-live/custom-signaling/build/setup-and-access/enable-service',
  'solutions/one-to-one-live/custom-signaling/overview/product-overview':
    '/zh-CN/solutions/one-to-one-live/custom-signaling',
  'solutions/one-to-one-live/custom-signaling/resources':
    '/zh-CN/solutions/one-to-one-live/custom-signaling/reference/downloads',
  'solutions/one-to-one-live/custom-signaling/solution-compare':
    '/zh-CN/solutions/one-to-one-live/custom-signaling/reference/solution-compare',
  'solutions/one-to-one-live/rtm/advanced-features/app-billing-policy':
    '/zh-CN/solutions/one-to-one-live/rtm/reference/app-billing-policy',
  'solutions/one-to-one-live/rtm/advanced-features/audio-scenario':
    '/zh-CN/solutions/one-to-one-live/rtm/build/customize-and-extend/audio-scenario',
  'solutions/one-to-one-live/rtm/advanced-features/integration-guideline':
    '/zh-CN/solutions/one-to-one-live/rtm/build/customize-and-extend/integration-guideline',
  'solutions/one-to-one-live/rtm/api/call-api':
    '/zh-CN/solutions/one-to-one-live/rtm/reference/call-api',
  'solutions/one-to-one-live/rtm/api/rtc-api':
    '/zh-CN/solutions/one-to-one-live/rtm/reference/rtc-api',
  'solutions/one-to-one-live/rtm/basic-features/showroom-to-one-to-one':
    '/zh-CN/solutions/one-to-one-live/rtm/build/implement-core-features/showroom-to-one-to-one',
  'solutions/one-to-one-live/rtm/basic-features/start-one-to-one':
    '/zh-CN/solutions/one-to-one-live/rtm/build/implement-core-features/start-one-to-one',
  'solutions/one-to-one-live/rtm/get-started/enable-service':
    '/zh-CN/solutions/one-to-one-live/rtm/build/setup-and-access/enable-service',
  'solutions/one-to-one-live/rtm/overview/product-overview':
    '/zh-CN/solutions/one-to-one-live/rtm',
  'solutions/one-to-one-live/rtm/resources':
    '/zh-CN/solutions/one-to-one-live/rtm/reference/downloads',
  'solutions/one-to-one-live/rtm/solution-compare':
    '/zh-CN/solutions/one-to-one-live/rtm/reference/solution-compare',
  'solutions/online-ktv/auikaraoke/reference/auikaraoke-api':
    '/zh-CN/api-reference/online-ktv/android/auikaraoke/api/auikaraoke-api',
  'solutions/online-ktv/auikaraoke/reference/lyrics-api':
    '/zh-CN/api-reference/online-ktv/android/auikaraoke/api/lyrics-api',
  'solutions/online-ktv/ktv-scenario/reference/ktv-api':
    '/zh-CN/api-reference/online-ktv/android/ktv-scenario/api/ktv-api',
  'solutions/online-ktv/ktv-scenario/reference/lyrics-api':
    '/zh-CN/api-reference/online-ktv/android/ktv-scenario/api/lyrics-api',
  'solutions/online-ktv/ktv-scenario/reference/music-content-center':
    '/zh-CN/api-reference/online-ktv/android/ktv-scenario/api/music-content-center',
  'solutions/online-ktv/ktv-scenario/reference/rtc-api':
    '/zh-CN/api-reference/online-ktv/android/ktv-scenario/api/rtc-api',
  'solutions/online-ktv/online-ktv-sdk/reference/lyrics-api':
    '/zh-CN/api-reference/online-ktv/android/online-ktv-sdk/api/lyrics-api',
  'solutions/online-ktv/online-ktv-sdk/reference/music-content-center':
    '/zh-CN/api-reference/online-ktv/android/online-ktv-sdk/api/music-content-center',
  'solutions/online-ktv/online-ktv-sdk/reference/rtc-api':
    '/zh-CN/api-reference/online-ktv/android/online-ktv-sdk/api/rtc-api',
  'solutions/online-music-class/advanced-features/fish-eye':
    '/zh-CN/solutions/online-music-class/build/extend-karaoke/fish-eye',
  'solutions/online-music-class/api/fish-eye':
    '/zh-CN/solutions/online-music-class/reference/fish-eye',
  'solutions/online-music-class/get-started/enable-service':
    '/zh-CN/solutions/online-music-class/build/setup-and-access/enable-service',
  'solutions/online-music-class/overview/product-overview':
    '/zh-CN/solutions/online-music-class',
  'solutions/online-music-class/resources':
    '/zh-CN/solutions/online-music-class/reference/downloads',
  'solutions/ppt-transcoding/billing':
    '/zh-CN/solutions/ppt-transcoding/reference/billing',
  'solutions/ppt-transcoding/convert-ppt':
    '/zh-CN/solutions/ppt-transcoding/reference/convert-ppt',
  'solutions/ppt-transcoding/get-started/enable-service':
    '/zh-CN/solutions/ppt-transcoding/build/setup-and-access/enable-service',
  'solutions/ppt-transcoding/product-overview':
    '/zh-CN/solutions/ppt-transcoding',
  'solutions/ppt-transcoding/response-code':
    '/zh-CN/solutions/ppt-transcoding/reference/response-code',
  'solutions/ppt-transcoding/slide-api':
    '/zh-CN/solutions/ppt-transcoding/reference/slide-api',
  'solutions/showroom/advanced-features/audio-scenario':
    '/zh-CN/solutions/showroom/build/customize-and-extend/audio-scenario',
  'solutions/showroom/advanced-features/beauty/bytedance/integrate':
    '/zh-CN/solutions/showroom/build/customize-and-extend/beauty/bytedance/integrate',
  'solutions/showroom/advanced-features/beauty/bytedance/run-project':
    '/zh-CN/solutions/showroom/build/customize-and-extend/beauty/bytedance/run-project',
  'solutions/showroom/advanced-features/beauty/faceunity/integrate':
    '/zh-CN/solutions/showroom/build/customize-and-extend/beauty/faceunity/integrate',
  'solutions/showroom/advanced-features/beauty/faceunity/run-project':
    '/zh-CN/solutions/showroom/build/customize-and-extend/beauty/faceunity/run-project',
  'solutions/showroom/advanced-features/beauty/overview':
    '/zh-CN/solutions/showroom/build/customize-and-extend/beauty/overview',
  'solutions/showroom/advanced-features/beauty/sensetime/integrate':
    '/zh-CN/solutions/showroom/build/customize-and-extend/beauty/sensetime/integrate',
  'solutions/showroom/advanced-features/beauty/sensetime/run-project':
    '/zh-CN/solutions/showroom/build/customize-and-extend/beauty/sensetime/run-project',
  'solutions/showroom/advanced-features/hq-video':
    '/zh-CN/solutions/showroom/build/customize-and-extend/hq-video',
  'solutions/showroom/advanced-features/video-loader/guidance':
    '/zh-CN/solutions/showroom/build/customize-and-extend/video-loader/guidance',
  'solutions/showroom/advanced-features/video-loader/integrate':
    '/zh-CN/solutions/showroom/build/customize-and-extend/video-loader/integrate',
  'solutions/showroom/advanced-features/video-loader/overview':
    '/zh-CN/solutions/showroom/build/customize-and-extend/video-loader/overview',
  'solutions/showroom/advanced-features/video-loader/run-project':
    '/zh-CN/solutions/showroom/build/customize-and-extend/video-loader/run-project',
  'solutions/showroom/advanced-features/video-moderation':
    '/zh-CN/solutions/showroom/build/customize-and-extend/video-moderation',
  'solutions/showroom/api': '/zh-CN/solutions/showroom/reference/api',
  'solutions/showroom/basic-features/integrate-check-point':
    '/zh-CN/solutions/showroom/build/implement-core-features/integrate-check-point',
  'solutions/showroom/basic-features/integrate-showroom':
    '/zh-CN/solutions/showroom/build/implement-core-features/integrate-showroom',
  'solutions/showroom/get-started/enable-service':
    '/zh-CN/solutions/showroom/build/setup-and-access/enable-service',
  'solutions/showroom/overview/product-overview': '/zh-CN/solutions/showroom',
  'solutions/showroom/resources':
    '/zh-CN/solutions/showroom/reference/downloads',
  'solutions/small-classroom/overview/product-overview':
    '/zh-CN/solutions/small-classroom',
  'solutions/small-classroom/paas/architecture':
    '/zh-CN/solutions/small-classroom/build/paas/architecture',
  'solutions/small-classroom/paas/best-practices':
    '/zh-CN/solutions/small-classroom/build/paas/best-practices',
  'solutions/small-classroom/paas/integration-guide':
    '/zh-CN/solutions/small-classroom/build/paas/integration-guide',
  'solutions/smart-camera/advanced-feature':
    '/zh-CN/solutions/smart-camera/reference/advanced-feature',
  'solutions/smart-camera/api/api-overview':
    '/zh-CN/solutions/smart-camera/reference/api-overview',
  'solutions/smart-camera/get-started/enable-service':
    '/zh-CN/solutions/smart-camera/build/setup-and-access/enable-service',
  'solutions/smart-camera/overview/product-overview':
    '/zh-CN/solutions/smart-camera',
  'solutions/smart-camera/resources':
    '/zh-CN/solutions/smart-camera/reference/downloads',
  'solutions/smart-camera/value-added-feature/amazon-alexa':
    '/zh-CN/solutions/smart-camera/build/value-added-feature/amazon-alexa',
  'solutions/smart-camera/value-added-feature/google-assistant':
    '/zh-CN/solutions/smart-camera/build/value-added-feature/google-assistant',
  'solutions/smart-doorbell/apaas/apaas-overview':
    '/zh-CN/solutions/smart-doorbell/build/apaas/apaas-overview',
  'solutions/smart-doorbell/enable-service':
    '/zh-CN/solutions/smart-doorbell/build/setup-and-access/enable-service',
  'solutions/smart-doorbell/paas/advanced-feature':
    '/zh-CN/solutions/smart-doorbell/reference/advanced-feature',
  'solutions/smart-doorbell/paas/api/api-overview':
    '/zh-CN/solutions/smart-doorbell/reference/api-overview',
  'solutions/smart-doorbell/paas/get-started/quick-start':
    '/zh-CN/solutions/smart-doorbell/build/paas/get-started/quick-start',
  'solutions/smart-doorbell/paas/overview/paas-overview':
    '/zh-CN/solutions/smart-doorbell/build/paas/paas-overview',
  'solutions/smart-doorbell/paas/resources':
    '/zh-CN/solutions/smart-doorbell/reference/downloads',
  'solutions/smart-doorbell/paas/value-added-feature/amazon-alexa':
    '/zh-CN/solutions/smart-doorbell/build/paas/value-added-feature/amazon-alexa',
  'solutions/smart-doorbell/paas/value-added-feature/google-assistant':
    '/zh-CN/solutions/smart-doorbell/build/paas/value-added-feature/google-assistant',
  'solutions/smart-doorbell/product-overview':
    '/zh-CN/solutions/smart-doorbell',
  'solutions/smart-watch/api/api-overview':
    '/zh-CN/solutions/smart-watch/reference/api-overview',
  'solutions/smart-watch/get-started/enable-service':
    '/zh-CN/solutions/smart-watch/build/setup-and-access/enable-service',
  'solutions/smart-watch/overview/product-overview':
    '/zh-CN/solutions/smart-watch',
  'solutions/smart-watch/resources':
    '/zh-CN/solutions/smart-watch/reference/downloads',
  'solutions/status-page/overview/product-overview':
    '/zh-CN/solutions/status-page',
  'solutions/status-page/overview/release-notes':
    '/zh-CN/solutions/status-page/reference/release-notes',
  'solutions/status-page/user-guide':
    '/zh-CN/solutions/status-page/build/implement-core-features/user-guide',
  'solutions/teleoperation/api/device':
    '/zh-CN/solutions/teleoperation/reference/device',
  'solutions/teleoperation/api/operator':
    '/zh-CN/solutions/teleoperation/reference/operator',
  'solutions/teleoperation/get-started/device-linux':
    '/zh-CN/solutions/teleoperation/build/implement-core-features/device-linux',
  'solutions/teleoperation/get-started/enable-service':
    '/zh-CN/solutions/teleoperation/build/setup-and-access/enable-service',
  'solutions/teleoperation/get-started/operator-android':
    '/zh-CN/solutions/teleoperation/build/implement-core-features/operator-android',
  'solutions/teleoperation/get-started/operator-linux':
    '/zh-CN/solutions/teleoperation/build/implement-core-features/operator-linux',
  'solutions/teleoperation/overview/product-overview':
    '/zh-CN/solutions/teleoperation',
  'solutions/teleoperation/resources':
    '/zh-CN/solutions/teleoperation/reference/downloads',
  'solutions/voip-call/get-started/enable-service':
    '/zh-CN/solutions/voip-call/build/setup-and-access/enable-service',
  'solutions/voip-call/overview/product-overview': '/zh-CN/solutions/voip-call',
  'solutions/voip-call/user-guide/http-basic-auth':
    '/zh-CN/solutions/voip-call/build/setup-and-access/http-basic-auth',
  'solutions/voip-call/user-guide/license':
    '/zh-CN/solutions/voip-call/build/setup-and-access/license',
  'solutions/voip-call/user-guide/set-source-sink':
    '/zh-CN/solutions/voip-call/build/customize-and-extend/set-source-sink',
  'solutions/voip-call/webhook/receive-webhook':
    '/zh-CN/solutions/voip-call/build/monitor-events/receive-webhook',
  'solutions/voip-call/webhook/voip-events':
    '/zh-CN/solutions/voip-call/reference/voip-events',
};

const ZH_CN_PRODUCT_IA_PREFIX_REDIRECTS: Array<[string, string]> = [
  ['api-reference/sdks', '/zh-CN/reference/sdks'],
  ['api-reference/recipes', '/zh-CN/reference/demo'],
  ['reference/recipes', '/zh-CN/reference/demo'],
  ['api-reference/faq', '/zh-CN/reference/faq'],
  [
    'realtime-media/recording/cloud-recording',
    '/zh-CN/realtime-media/cloud-recording',
  ],
  [
    'realtime-media/recording/local-server-recording',
    '/zh-CN/realtime-media/local-server-recording',
  ],
];

export function resolveZhCnProductIaRedirect(
  locale: string,
  tab: string,
  slugSegments: string[],
) {
  if (locale !== 'zh-CN') {
    return null;
  }

  const path = `${tab}/${slugSegments.join('/')}`;

  for (const [
    sourcePrefix,
    targetPrefix,
  ] of ZH_CN_PRODUCT_IA_PREFIX_REDIRECTS) {
    if (path === sourcePrefix || path.startsWith(`${sourcePrefix}/`)) {
      return `${targetPrefix}${path.slice(sourcePrefix.length)}`;
    }
  }

  return ZH_CN_PRODUCT_IA_REDIRECTS[path] ?? null;
}

export { ZH_CN_PRODUCT_IA_REDIRECTS };
