/* eslint-disable */
// This file is generated by scripts/build-openapi-operations-manifest.mjs

export const OPENAPI_ROUTE_MANIFEST = 
{
  "convoai": {
    "en": {
      "agent-interrupt": {
        "description": "Interrupt the specified agent from speaking or thinking.",
        "method": "post",
        "path": "/v2/projects/{appid}/agents/{agentId}/interrupt",
        "routeLeaf": "interrupt",
        "title": "Interrupt the agent"
      },
      "agent-speak": {
        "description": "Let the specified agent broadcast a custom message.\r\n\r\nDuring the conversation with the agent, calling this interface allows the agent to use the TTS module to immediately broadcast a custom message. After the agent receives the request, the broadcast behavior will interrupt the current speaking and thinking process.",
        "method": "post",
        "path": "/v2/projects/{appid}/agents/{agentId}/speak",
        "routeLeaf": "speak",
        "title": "Broadcast a message using TTS"
      },
      "agent-think": {
        "description": "Send a custom text command to the specified agent.\n\nThe interface will inject incoming text as user input into the current conversation link, and the conversational AI engine will continue to reason and respond according to the processing logic of ordinary user input. You can use this interface to implement scenarios such as implicit command injection, client-side event triggering, and voice and text collaboration.",
        "method": "post",
        "path": "/v2/projects/{appid}/agents/{agentId}/think",
        "routeLeaf": "think",
        "title": "Send a custom instruction"
      },
      "agent-update": {
        "description": "Update some parameter configurations of the specified running agent.",
        "method": "post",
        "path": "/v2/projects/{appid}/agents/{agentId}/update",
        "routeLeaf": "update",
        "title": "Update agent configuration"
      },
      "get-agent-list": {
        "description": "Retrieve a list of agents that match specified criteria.\n> This interface only supports querying the list of agents created within the last 7 days.",
        "method": "get",
        "path": "/v2/projects/{appid}/agents",
        "routeLeaf": "list",
        "title": "Retrieve a list of agents"
      },
      "get-history": {
        "description": "Capture the short-term memory of the conversation between the user and the agent.\r\nYou can call this API during the running of the agent (`RUNNING`) to obtain the short-term memory information stored until the creation of the agent, including:\r\n- timestamps when the agent was created and stopped\r\n- User and agent conversation messages",
        "method": "get",
        "path": "/v2/projects/{appid}/agents/{agentId}/history",
        "routeLeaf": "history",
        "title": "Retrieve agent history"
      },
      "get-turns": {
        "description": "After the session with the agent ends, call this interface to query the dialogue round information of this session, including the start information, end information, and performance indicators of each dialogue round.\n> Only supports querying sessions within 7 days.",
        "method": "get",
        "path": "/v2/projects/{appid}/agents/{agentId}/turns",
        "routeLeaf": "turns",
        "title": "Query conversation turn information"
      },
      "query-agent-status": {
        "description": "Query the current running status of the specified agent instance.",
        "method": "get",
        "path": "/v2/projects/{appid}/agents/{agentId}",
        "routeLeaf": "query",
        "title": "Query agent status"
      },
      "start-agent": {
        "description": "Create a Conversational AI agent instance and join the RTC channel.",
        "method": "post",
        "path": "/v2/projects/{appid}/join",
        "routeLeaf": "join",
        "title": "Start a conversational AI agent"
      },
      "stop-agent": {
        "description": "Stops the specified conversational agent instance and causes the agent to exit the RTC channel.",
        "method": "post",
        "path": "/v2/projects/{appid}/agents/{agentId}/leave",
        "routeLeaf": "leave",
        "title": "Stop a conversational AI agent"
      }
    },
    "zh-CN": {
      "agent-interrupt": {
        "description": "打断指定智能体说话或思考。",
        "method": "post",
        "path": "/v2/projects/{appid}/agents/{agentId}/interrupt",
        "routeLeaf": "interrupt",
        "title": "打断智能体"
      },
      "agent-speak": {
        "description": "让指定智能体播报自定义消息。\r\n\r\n与智能体对话期间，调用该接口可以让智能体使用 TTS 模块立刻播报自定义消息。智能体收到请求后，播报行为会打断当前说话和思考流程。",
        "method": "post",
        "path": "/v2/projects/{appid}/agents/{agentId}/speak",
        "routeLeaf": "speak",
        "title": "播报自定义消息"
      },
      "agent-think": {
        "description": "向指定智能体发送一段自定义文本指令。\n\n该接口会将传入文本作为用户输入注入当前对话链路，并由对话式 AI 引擎继续按照普通用户输入的处理逻辑进行推理和响应。你可以使用该接口实现隐式指令注入、客户端事件触发和语音与文本协同等场景。\n",
        "method": "post",
        "path": "/v2/projects/{appid}/agents/{agentId}/think",
        "routeLeaf": "think",
        "title": "发送自定义指令"
      },
      "agent-update": {
        "description": "更新指定运行中智能体的部分参数配置。",
        "method": "post",
        "path": "/v2/projects/{appid}/agents/{agentId}/update",
        "routeLeaf": "update",
        "title": "更新智能体配置"
      },
      "get-agent-list": {
        "description": "检索符合指定条件的智能体列表。\n> 该接口仅支持查询最近 7 天内创建的智能体列表。\n",
        "method": "get",
        "path": "/v2/projects/{appid}/agents",
        "routeLeaf": "list",
        "title": "获取智能体列表"
      },
      "get-history": {
        "description": "获取用户和智能体对话的短期记忆。\r\n你可以在智能体运行期间 (`RUNNING`) 调用该 API 获取智能体创建到现在储存的短期记忆信息，包括：\r\n- 智能体创建和停止的时间戳\r\n- 用户和智能体对话消息",
        "method": "get",
        "path": "/v2/projects/{appid}/agents/{agentId}/history",
        "routeLeaf": "history",
        "title": "获取智能体短期记忆"
      },
      "get-turns": {
        "description": "在与智能体会话结束后，调用该接口查询本次会话的对话轮次信息，包含每个对话轮次的开始信息、结束信息、性能指标。\n> 仅支持查询 7 天内的会话。\n",
        "method": "get",
        "path": "/v2/projects/{appid}/agents/{agentId}/turns",
        "routeLeaf": "turns",
        "title": "查询对话轮次信息"
      },
      "query-agent-status": {
        "description": "查询指定智能体实例的当前运行状态。",
        "method": "get",
        "path": "/v2/projects/{appid}/agents/{agentId}",
        "routeLeaf": "query",
        "title": "查询智能体状态"
      },
      "start-agent": {
        "description": "创建一个对话式智能体 (Conversational AI agent) 实例，并加入 RTC 频道。",
        "method": "post",
        "path": "/v2/projects/{appid}/join",
        "routeLeaf": "join",
        "title": "创建对话式智能体"
      },
      "stop-agent": {
        "description": "停止指定的对话式智能体实例，并让智能体退出 RTC 频道。",
        "method": "post",
        "path": "/v2/projects/{appid}/agents/{agentId}/leave",
        "routeLeaf": "leave",
        "title": "停止对话式智能体"
      }
    }
  }
} as const;
