/* eslint-disable */
// This file is generated by scripts/build-openapi-operations-manifest.mjs

export const OPENAPI_METHODS_MANIFEST = 
{
  "convoai": {
    "en": {
      "agent-interrupt": "POST",
      "agent-speak": "POST",
      "agent-think": "POST",
      "agent-update": "POST",
      "get-agent-list": "GET",
      "get-history": "GET",
      "get-turns": "GET",
      "query-agent-status": "GET",
      "start-agent": "POST",
      "stop-agent": "POST"
    },
    "zh-CN": {
      "agent-interrupt": "POST",
      "agent-speak": "POST",
      "agent-think": "POST",
      "agent-update": "POST",
      "get-agent-list": "GET",
      "get-history": "GET",
      "get-turns": "GET",
      "query-agent-status": "GET",
      "start-agent": "POST",
      "stop-agent": "POST"
    }
  }
} as const;
