export type ApiReferenceCardType = 'client' | 'server';

export type ApiReferenceKind = 'client-api' | 'restful-api' | 'server-sdk';

export type ApiReferenceCardEntry = {
  apiType: ApiReferenceKind;
  href: string;
  platform: string;
  platformId: string;
  product: string;
  productId: string;
};

export const zhCNApiReferenceCards: Record<
  ApiReferenceCardType,
  ApiReferenceCardEntry[]
> = {
  client: [
    entry(
      '对话式 AI',
      'conversational-ai',
      'Android',
      'android',
      'client-api',
      '/zh-CN/api-reference/conversational-ai/android/overview',
    ),
    entry(
      '对话式 AI',
      'conversational-ai',
      'iOS',
      'ios',
      'client-api',
      '/zh-CN/api-reference/conversational-ai/ios/overview',
    ),
    entry(
      '对话式 AI',
      'conversational-ai',
      'Web',
      'web',
      'client-api',
      '/zh-CN/api-reference/conversational-ai/web/overview',
    ),
    entry(
      '实时互动 RTC',
      'rtc',
      'Android',
      'android',
      'client-api',
      '/zh-CN/api-reference/rtc/android/rtc-api-overview',
    ),
    entry(
      '实时互动 RTC',
      'rtc',
      'iOS',
      'ios',
      'client-api',
      '/zh-CN/api-reference/rtc/ios/rtc-api-overview',
    ),
    entry(
      '实时互动 RTC',
      'rtc',
      'macOS',
      'macos',
      'client-api',
      '/zh-CN/api-reference/rtc/macos/rtc-api-overview',
    ),
    entry(
      '实时互动 RTC',
      'rtc',
      'C++（全平台）',
      'cpp',
      'client-api',
      '/zh-CN/api-reference/rtc/cpp-all-platforms/rtc-api-overview',
    ),
    entry(
      '实时互动 RTC',
      'rtc',
      'C#（Windows）',
      'csharp',
      'client-api',
      '/zh-CN/api-reference/rtc/csharp-windows/rtc-api-overview',
    ),
    entry(
      '实时互动 RTC',
      'rtc',
      'Electron',
      'electron',
      'client-api',
      '/zh-CN/api-reference/rtc/electron/rtc-api-overview',
    ),
    entry(
      '实时互动 RTC',
      'rtc',
      'Unity',
      'unity',
      'client-api',
      '/zh-CN/api-reference/rtc/unity/rtc-api-overview',
    ),
    entry(
      '实时互动 RTC',
      'rtc',
      'Flutter',
      'flutter',
      'client-api',
      '/zh-CN/api-reference/rtc/flutter/rtc-api-overview',
    ),
    entry(
      '实时互动 RTC',
      'rtc',
      'React Native',
      'react-native',
      'client-api',
      '/zh-CN/api-reference/rtc/react-native/rtc-api-overview',
    ),
    entry(
      '实时互动 RTC',
      'rtc',
      'Unreal (C++)',
      'unreal-cpp',
      'client-api',
      '/zh-CN/api-reference/rtc/unreal-cpp/rtc-api-overview',
    ),
    entry(
      '实时互动 RTC',
      'rtc',
      'Unreal (Blueprint)',
      'unreal-blueprint',
      'client-api',
      '/zh-CN/api-reference/rtc/unreal-blueprint/rtc-api-overview',
    ),
    entry(
      '实时互动 RTC',
      'rtc',
      'HarmonyOS',
      'harmonyos',
      'client-api',
      '/zh-CN/api-reference/rtc/harmonyos/rtc-api-overview',
    ),
    entry(
      '实时互动 RTC',
      'rtc',
      'Web',
      'web',
      'client-api',
      '/zh-CN/api-reference/rtc/react-sdk/overview',
    ),
    entry(
      '实时消息 RTM',
      'rtm',
      'Android',
      'android',
      'client-api',
      '/zh-CN/api-reference/rtm/android/configuration',
    ),
    entry(
      '实时消息 RTM',
      'rtm',
      'iOS',
      'ios',
      'client-api',
      '/zh-CN/api-reference/rtm/ios/configuration',
    ),
    entry(
      '实时消息 RTM',
      'rtm',
      'Web',
      'web',
      'client-api',
      '/zh-CN/api-reference/rtm/web/configuration',
    ),
    entry(
      '实时消息 RTM',
      'rtm',
      'HarmonyOS',
      'harmonyos',
      'client-api',
      '/zh-CN/api-reference/rtm/harmonyos/configuration',
    ),
    entry(
      '实时消息 RTM',
      'rtm',
      'Unity',
      'unity',
      'client-api',
      '/zh-CN/api-reference/rtm/unity/configuration',
    ),
    entry(
      '实时消息 RTM',
      'rtm',
      'Flutter',
      'flutter',
      'client-api',
      '/zh-CN/api-reference/rtm/flutter/configuration',
    ),
    entry(
      '实时消息 RTM',
      'rtm',
      'React Native',
      'react-native',
      'client-api',
      '/zh-CN/api-reference/rtm/react-native/configuration',
    ),
    entry(
      '实时消息 RTM',
      'rtm',
      'C++',
      'cpp',
      'client-api',
      '/zh-CN/api-reference/rtm/cpp/configuration',
    ),
    entry(
      '实时消息 RTM',
      'rtm',
      'Swift',
      'swift',
      'client-api',
      '/zh-CN/api-reference/rtm/swift/configuration',
    ),
    entry(
      '互动白板',
      'whiteboard',
      'Android',
      'android',
      'client-api',
      '/zh-CN/api-reference/whiteboard/fastboard/android',
    ),
    entry(
      '互动白板',
      'whiteboard',
      'iOS',
      'ios',
      'client-api',
      '/zh-CN/api-reference/whiteboard/fastboard/ios',
    ),
    entry(
      '互动白板',
      'whiteboard',
      'Web',
      'web',
      'client-api',
      '/zh-CN/api-reference/whiteboard/fastboard/web',
    ),
    entry(
      '会议',
      'meeting',
      'Android',
      'android',
      'client-api',
      '/zh-CN/api-reference/meeting/android',
    ),
    entry(
      '会议',
      'meeting',
      'iOS',
      'ios',
      'client-api',
      '/zh-CN/api-reference/meeting/ios',
    ),
    entry(
      '会议',
      'meeting',
      'Electron',
      'electron',
      'client-api',
      '/zh-CN/api-reference/meeting/electron',
    ),
    entry(
      '私密房',
      'private-room',
      'Android',
      'android',
      'client-api',
      '/zh-CN/api-reference/private-room/android',
    ),
    entry(
      '私密房',
      'private-room',
      'iOS',
      'ios',
      'client-api',
      '/zh-CN/api-reference/private-room/ios',
    ),
    entry(
      '灵动课堂',
      'flexible-classroom',
      'Android',
      'android',
      'client-api',
      '/zh-CN/api-reference/flexible-classroom/android/api-reference/classroom-sdk',
    ),
    entry(
      '灵动课堂',
      'flexible-classroom',
      'iOS',
      'ios',
      'client-api',
      '/zh-CN/api-reference/flexible-classroom/ios/api-reference/classroom-sdk',
    ),
    entry(
      '灵动课堂',
      'flexible-classroom',
      'Web',
      'web',
      'client-api',
      '/zh-CN/api-reference/flexible-classroom/web/api-reference/classroom-sdk',
    ),
    entry(
      '灵动课堂',
      'flexible-classroom',
      'Electron',
      'electron',
      'client-api',
      '/zh-CN/api-reference/flexible-classroom/electron/api-reference/classroom-sdk',
    ),
  ],
  server: [
    entry(
      '对话式 AI',
      'conversational-ai',
      'Go',
      'go',
      'server-sdk',
      '/zh-CN/api-reference/conversational-ai/agent-go',
    ),
    entry(
      '对话式 AI',
      'conversational-ai',
      'Python',
      'python',
      'server-sdk',
      '/zh-CN/api-reference/conversational-ai/agent-python',
    ),
    entry(
      '对话式 AI',
      'conversational-ai',
      'TypeScript',
      'typescript',
      'server-sdk',
      '/zh-CN/api-reference/conversational-ai/agent-typescript',
    ),
    entry(
      '对话式 AI',
      'conversational-ai',
      'Go REST Client',
      'go',
      'server-sdk',
      '/zh-CN/api-reference/conversational-ai/restclient-go/overview',
    ),
    entry(
      '对话式 AI',
      'conversational-ai',
      'Java REST Client',
      'java',
      'server-sdk',
      '/zh-CN/api-reference/conversational-ai/restclient-java/overview',
    ),
    entry(
      '对话式 AI',
      'conversational-ai',
      'RESTful API',
      'restful-api',
      'restful-api',
      '/zh-CN/api-reference/api-ref/conversational-ai',
    ),
    entry(
      'RTC 服务端 SDK',
      'rtc-server-sdk',
      'Go',
      'go',
      'server-sdk',
      '/zh-CN/api-reference/rtc-server-sdk/go-api/overview.go',
    ),
    entry(
      'RTC 服务端 SDK',
      'rtc-server-sdk',
      'Python',
      'python',
      'server-sdk',
      '/zh-CN/api-reference/rtc-server-sdk/python-api/overview.python',
    ),
    entry(
      '云端录制',
      'cloud-recording',
      'Go',
      'go',
      'server-sdk',
      '/zh-CN/api-reference/cloud-recording/go-api/overview.go',
    ),
    entry(
      '云端录制',
      'cloud-recording',
      'Java',
      'java',
      'server-sdk',
      '/zh-CN/api-reference/cloud-recording/java-api/overview.java',
    ),
    entry(
      '云端录制',
      'cloud-recording',
      'RESTful API',
      'restful-api',
      'restful-api',
      '/zh-CN/api-reference/api-ref/cloud-recording',
    ),
    entry(
      '本地服务端录制',
      'local-server-recording',
      'Java',
      'java',
      'server-sdk',
      '/zh-CN/api-reference/local-server-recording/java/api-overview',
    ),
    entry(
      '本地服务端录制',
      'local-server-recording',
      'C++',
      'cpp',
      'server-sdk',
      '/zh-CN/api-reference/local-server-recording/cpp/api-overview',
    ),
    entry(
      '实时互动 RTC',
      'rtc',
      'RESTful API',
      'restful-api',
      'restful-api',
      '/zh-CN/api-reference/api-ref/rtc',
    ),
    entry(
      '实时消息 RTM',
      'rtm',
      'RESTful API',
      'restful-api',
      'restful-api',
      '/zh-CN/api-reference/api-ref/signaling/publish',
    ),
    entry(
      '互动白板',
      'whiteboard',
      'RESTful API',
      'restful-api',
      'restful-api',
      '/zh-CN/api-reference/api-ref/whiteboard/restful',
    ),
    entry(
      '融合 CDN 直播',
      'fusion-cdn',
      'RESTful API',
      'restful-api',
      'restful-api',
      '/zh-CN/api-reference/api-ref/fusion-cdn',
    ),
    entry(
      '旁路推流',
      'media-push',
      'RESTful API',
      'restful-api',
      'restful-api',
      '/zh-CN/api-reference/api-ref/media-push',
    ),
    entry(
      '输入在线媒体流',
      'media-pull',
      'RESTful API',
      'restful-api',
      'restful-api',
      '/zh-CN/api-reference/api-ref/media-pull',
    ),
    entry(
      '云端转码',
      'cloud-transcoding',
      'RESTful API',
      'restful-api',
      'restful-api',
      '/zh-CN/api-reference/api-ref/cloud-transcoding',
    ),
    entry(
      '实时转录翻译',
      'speech-to-text',
      'RESTful API',
      'restful-api',
      'restful-api',
      '/zh-CN/api-reference/api-ref/speech-to-text',
    ),
    entry(
      'RTMP 网关',
      'rtmp-gateway',
      'RESTful API',
      'restful-api',
      'restful-api',
      '/zh-CN/api-reference/api-ref/rtmp-gateway',
    ),
    entry(
      'PPT 转码服务',
      'ppt-conversion-service',
      'RESTful API',
      'restful-api',
      'restful-api',
      '/zh-CN/api-reference/api-ref/ppt-conversion-service',
    ),
    entry(
      '控制台',
      'console',
      'RESTful API',
      'restful-api',
      'restful-api',
      '/zh-CN/api-reference/api-ref/console',
    ),
    entry(
      '水晶球',
      'analytics',
      'RESTful API',
      'restful-api',
      'restful-api',
      '/zh-CN/api-reference/api-ref/agora-analytics',
    ),
    entry(
      '灵动课堂',
      'flexible-classroom',
      'RESTful API',
      'restful-api',
      'restful-api',
      '/zh-CN/api-reference/flexible-classroom/restful-api/api-classroom',
    ),
    entry(
      '弹幕玩法',
      'danmaku',
      'RESTful API',
      'restful-api',
      'restful-api',
      '/zh-CN/api-reference/api-ref/danmaku',
    ),
    entry(
      'VoIP 呼叫服务',
      'voip-callkit',
      'RESTful API',
      'restful-api',
      'restful-api',
      '/zh-CN/api-reference/api-ref/voip-callkit',
    ),
  ],
};

function entry(
  product: string,
  productId: string,
  platform: string,
  platformId: string,
  apiType: ApiReferenceKind,
  href: string,
): ApiReferenceCardEntry {
  return { apiType, href, platform, platformId, product, productId };
}
