import fs from 'node:fs/promises';
import path from 'node:path';
import yaml from 'js-yaml';
import { auditDocsLinks } from '../../audit-doc-links.mjs';
import { API_CENTER_WARNING_DEFINITIONS } from './migration-framework.mjs';

export const API_CENTER_OWNERSHIP_LEDGERS = [
  'docs/migration/api-center-generated-files.json',
  'docs/migration/api-center-manual-generated-files.json',
  'docs/migration/api-center-navigation-generated-files.json',
];

function increment(target, key, amount = 1) {
  target[key] = (target[key] ?? 0) + amount;
}

function splitFrontmatter(source) {
  const match = String(source).match(/^---\r?\n([\s\S]*?)\r?\n---\s*(?:\r?\n|$)/);
  if (!match) return null;
  try {
    return yaml.load(match[1]) ?? null;
  } catch {
    return null;
  }
}

function stableObject(value) {
  if (Array.isArray(value)) return value.map(stableObject);
  if (!value || typeof value !== 'object') return value;
  return Object.fromEntries(
    Object.keys(value)
      .sort()
      .map((key) => [key, stableObject(value[key])]),
  );
}

export function apiCenterLinkAuditMarkdown(report) {
  const lines = [
    '# API Center Scoped Link Audit',
    '',
    '> Generated by `scripts/audit-api-center-links.mjs`. Do not edit by hand.',
    '',
    `- Owned MDX pages: ${report.counts.ownedMdxPages}`,
    `- Links checked: ${report.counts.links}`,
    `- Invalid links: ${report.counts.invalidLinks}`,
    `- Missing local paths: ${report.counts.missingLocalPaths}`,
    `- Missing fragments: ${report.counts.missingFragments}`,
    `- Errors: ${report.counts.errors}`,
    `- Warning-severity frontmatter signals: ${report.counts.warnings}`,
    '',
    '## Migration/output types',
    '',
    ...Object.entries(report.outputTypes).map(
      ([type, count]) => `- \`${type}\`: ${count}`,
    ),
    '',
    '## Warning explanations',
    '',
    ...(Object.keys(report.warningSummary).length
      ? Object.entries(report.warningSummary).map(
          ([code, value]) =>
            `- \`${code}\` (${value.count}, ${value.severity}): ${value.explanation}`,
        )
      : ['- None.']),
    '',
    '## Link issues',
    '',
  ];
  if (report.issues.length === 0) {
    lines.push('- None.', '');
  } else {
    lines.push(
      '| Type | Source | Target | Reason |',
      '| --- | --- | --- | --- |',
    );
    for (const issue of report.issues) {
      lines.push(
        `| ${issue.type ?? 'internal'} | \`${issue.sourcePath}\` | \`${issue.href}\` | ${issue.reason} |`,
      );
    }
    lines.push('');
  }
  return `${lines.join('\n')}\n`;
}

export async function auditApiCenterLinks({
  repoRoot = process.cwd(),
  ownershipPaths = API_CENTER_OWNERSHIP_LEDGERS,
} = {}) {
  const records = [];
  for (const ownershipPath of ownershipPaths) {
    const ownership = JSON.parse(
      await fs.readFile(path.resolve(repoRoot, ownershipPath), 'utf8'),
    );
    records.push(...(ownership.files ?? []));
  }
  const uniqueRecords = new Map();
  for (const record of records) uniqueRecords.set(record.targetPath, record);
  const mdxRecords = [...uniqueRecords.values()].filter((record) =>
    record.targetPath.startsWith('content/docs/') && record.targetPath.endsWith('.mdx'),
  );
  const sourcePaths = mdxRecords.map((record) =>
    record.targetPath.replace(/^content\/docs\//, ''),
  );
  const outputTypes = {};
  for (const record of uniqueRecords.values()) increment(outputTypes, record.type);

  const warningCounts = {};
  for (const record of mdxRecords) {
    const source = await fs.readFile(path.resolve(repoRoot, record.targetPath), 'utf8');
    const frontmatter = splitFrontmatter(source);
    for (const warning of frontmatter?._migration?.warnings ?? []) {
      if (warning?.code) increment(warningCounts, warning.code);
    }
  }
  const warningSummary = Object.fromEntries(
    Object.entries(warningCounts)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([code, count]) => [
        code,
        {
          count,
          severity: API_CENTER_WARNING_DEFINITIONS[code]?.severity ?? 'warning',
          explanation:
            API_CENTER_WARNING_DEFINITIONS[code]?.explanation ??
            'No warning definition is registered.',
        },
      ]),
  );
  const stats = auditDocsLinks({
    docsRoot: path.resolve(repoRoot, 'content/docs'),
    sourcePaths,
  });
  const missingLocalPaths =
    stats.missingRelativeMarkdownLinks.length + stats.missingRootLinks.length;
  const report = stableObject({
    schemaVersion: 1,
    ownershipPaths,
    counts: {
      ownedMdxPages: mdxRecords.length,
      links: stats.totalLinks,
      invalidLinks: stats.invalidLinks.length,
      missingLocalPaths,
      missingFragments: stats.missingHashLinks.length,
      errors: stats.invalidLinks.length,
      warnings: Object.values(warningSummary)
        .filter((value) => value.severity === 'warning')
        .reduce((sum, value) => sum + value.count, 0),
    },
    outputTypes,
    warningSummary,
    issues: stats.invalidLinks,
  });
  return { report, markdown: apiCenterLinkAuditMarkdown(report) };
}
