import fs from 'node:fs/promises';
import path from 'node:path';
import yaml from 'js-yaml';
import { auditDocsLinks } from '../../audit-doc-links.mjs';
import { findLegacyBodyLinks } from './legacy-links.mjs';
import { API_CENTER_WARNING_DEFINITIONS } from './migration-framework.mjs';

export const API_CENTER_OWNERSHIP_LEDGERS = [
  'docs/migration/api-center-generated-files.json',
  'docs/migration/api-center-manual-generated-files.json',
  'docs/migration/api-center-navigation-generated-files.json',
];

function increment(target, key, amount = 1) {
  target[key] = (target[key] ?? 0) + amount;
}

function splitFrontmatter(source) {
  const match = String(source).match(
    /^---\r?\n([\s\S]*?)\r?\n---\s*(?:\r?\n|$)/,
  );
  if (!match) return null;
  try {
    return yaml.load(match[1]) ?? null;
  } catch {
    return null;
  }
}

function stableObject(value) {
  if (Array.isArray(value)) return value.map(stableObject);
  if (!value || typeof value !== 'object') return value;
  return Object.fromEntries(
    Object.keys(value)
      .sort()
      .map((key) => [key, stableObject(value[key])]),
  );
}

export function apiCenterLinkAuditMarkdown(report) {
  const lines = [
    '# API Center Scoped Link Audit',
    '',
    '> Generated by `scripts/audit-api-center-links.mjs`. Do not edit by hand.',
    '',
    `- Owned MDX pages: ${report.counts.ownedMdxPages}`,
    `- Visible MDX pages: ${report.counts.visibleMdxPages}`,
    `- Preserved/reused MDX pages: ${report.counts.preservedMdxPages}`,
    `- Links checked: ${report.counts.links}`,
    `- Old-site body links: ${report.counts.legacyOldSiteBodyLinks}`,
    `- Invalid links: ${report.counts.invalidLinks}`,
    `- Missing local paths: ${report.counts.missingLocalPaths}`,
    `- Missing fragments: ${report.counts.missingFragments}`,
    `- Errors: ${report.counts.errors}`,
    `- Warning-severity frontmatter signals: ${report.counts.warnings}`,
    '',
    '## Migration/output types',
    '',
    ...Object.entries(report.outputTypes).map(
      ([type, count]) => `- \`${type}\`: ${count}`,
    ),
    '',
    '## Warning explanations',
    '',
    ...(Object.keys(report.warningSummary).length
      ? Object.entries(report.warningSummary).map(
          ([code, value]) =>
            `- \`${code}\` (${value.count}, ${value.severity}): ${value.explanation}`,
        )
      : ['- None.']),
    '',
    '## Link issues',
    '',
  ];
  if (report.issues.length === 0) {
    lines.push('- None.', '');
  } else {
    lines.push(
      '| Type | Source | Target | Reason |',
      '| --- | --- | --- | --- |',
    );
    for (const issue of report.issues) {
      lines.push(
        `| ${issue.type ?? 'internal'} | \`${issue.sourcePath}\` | \`${issue.href}\` | ${issue.reason} |`,
      );
    }
    lines.push('');
  }
  return `${lines.join('\n')}\n`;
}

export async function auditApiCenterLinks({
  repoRoot = process.cwd(),
  ownershipPaths = API_CENTER_OWNERSHIP_LEDGERS,
  manifestPath = 'docs/migration/api-center-html-manifest.json',
} = {}) {
  const records = [];
  for (const ownershipPath of ownershipPaths) {
    const ownership = JSON.parse(
      await fs.readFile(path.resolve(repoRoot, ownershipPath), 'utf8'),
    );
    records.push(...(ownership.files ?? []));
  }
  const uniqueRecords = new Map();
  for (const record of records) uniqueRecords.set(record.targetPath, record);
  const ownedTargets = new Set(uniqueRecords.keys());
  const ownedRecords = [...uniqueRecords.values()];
  try {
    const manifest = JSON.parse(
      await fs.readFile(path.resolve(repoRoot, manifestPath), 'utf8'),
    );
    for (const page of manifest.pageEvidence ?? []) {
      const resolution = page.sourceResolution;
      if (
        page.aliasOf ||
        !resolution?.targetExists ||
        !resolution.targetPath?.startsWith('content/docs/') ||
        !/\.mdx?$/i.test(resolution.targetPath)
      ) {
        continue;
      }
      if (!uniqueRecords.has(resolution.targetPath)) {
        uniqueRecords.set(resolution.targetPath, {
          targetPath: resolution.targetPath,
          type: resolution.type ?? 'preserved-existing',
        });
      }
    }
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
  }
  const mdxRecords = [...uniqueRecords.values()].filter(
    (record) =>
      record.targetPath.startsWith('content/docs/') &&
      record.targetPath.endsWith('.mdx'),
  );
  const ownedMdxRecords = ownedRecords.filter(
    (record) =>
      record.targetPath.startsWith('content/docs/') &&
      record.targetPath.endsWith('.mdx'),
  );
  const sourcePaths = ownedMdxRecords.map((record) =>
    record.targetPath.replace(/^content\/docs\//, ''),
  );
  const outputTypes = {};
  for (const record of ownedRecords) increment(outputTypes, record.type);

  const warningCounts = {};
  for (const record of ownedMdxRecords) {
    const source = await fs.readFile(
      path.resolve(repoRoot, record.targetPath),
      'utf8',
    );
    const frontmatter = splitFrontmatter(source);
    for (const warning of frontmatter?._migration?.warnings ?? []) {
      if (warning?.code) increment(warningCounts, warning.code);
    }
  }
  const warningSummary = Object.fromEntries(
    Object.entries(warningCounts)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([code, count]) => [
        code,
        {
          count,
          severity: API_CENTER_WARNING_DEFINITIONS[code]?.severity ?? 'warning',
          explanation:
            API_CENTER_WARNING_DEFINITIONS[code]?.explanation ??
            'No warning definition is registered.',
        },
      ]),
  );
  const stats = auditDocsLinks({
    docsRoot: path.resolve(repoRoot, 'content/docs'),
    sourcePaths,
  });
  const missingLocalPaths =
    stats.missingRelativeMarkdownLinks.length + stats.missingRootLinks.length;
  const legacyBodyLinks = [];
  for (const record of mdxRecords) {
    const source = await fs.readFile(
      path.resolve(repoRoot, record.targetPath),
      'utf8',
    );
    legacyBodyLinks.push(
      ...findLegacyBodyLinks(source, {
        sourcePath: record.targetPath.replace(/^content\/docs\//, ''),
      }),
    );
  }
  const issues = [...stats.invalidLinks];
  const issuesByKey = new Map(
    issues.map((issue) => [`${issue.sourcePath}\u0000${issue.href}`, issue]),
  );
  for (const link of legacyBodyLinks) {
    const key = `${link.sourcePath}\u0000${link.href}`;
    const existing = issuesByKey.get(key);
    if (existing) {
      existing.reason = 'old-site-body-link';
      continue;
    }
    const issue = {
      ...link,
      reason: 'old-site-body-link',
      target: link.href,
      type: 'internal',
    };
    issuesByKey.set(key, issue);
    issues.push(issue);
  }
  const report = stableObject({
    schemaVersion: 2,
    ownershipPaths,
    counts: {
      ownedMdxPages: ownedMdxRecords.length,
      visibleMdxPages: mdxRecords.length,
      preservedMdxPages: mdxRecords.filter(
        (record) => !ownedTargets.has(record.targetPath),
      ).length,
      legacyOldSiteBodyLinks: legacyBodyLinks.length,
      links: stats.totalLinks,
      invalidLinks: stats.invalidLinks.length,
      missingLocalPaths,
      missingFragments: stats.missingHashLinks.length,
      errors: issues.length,
      warnings: Object.values(warningSummary)
        .filter((value) => value.severity === 'warning')
        .reduce((sum, value) => sum + value.count, 0),
    },
    outputTypes,
    warningSummary,
    issues,
  });
  return { report, markdown: apiCenterLinkAuditMarkdown(report) };
}
