import fs from 'node:fs/promises';
import path from 'node:path';
import yaml from 'js-yaml';

const HTTP_METHODS = new Set([
  'delete',
  'get',
  'head',
  'options',
  'patch',
  'post',
  'put',
  'trace',
]);

function stableJson(value) {
  if (Array.isArray(value)) return value.map(stableJson);
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.keys(value)
        .sort()
        .map((key) => [key, stableJson(value[key])]),
    );
  }
  return value;
}

function json(value) {
  return `${JSON.stringify(stableJson(value), null, 2)}\n`;
}

async function exists(filePath) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

function operations(document) {
  const result = new Map();
  const duplicates = [];
  for (const [pathname, pathItem] of Object.entries(document.paths ?? {})) {
    for (const [method, operation] of Object.entries(pathItem ?? {})) {
      if (!HTTP_METHODS.has(method.toLowerCase()) || !operation?.operationId) {
        continue;
      }
      const record = {
        operationId: operation.operationId,
        method: method.toUpperCase(),
        pathname,
        summary: operation.summary ?? '',
        description: operation.description ?? '',
      };
      if (result.has(record.operationId)) duplicates.push(record.operationId);
      else result.set(record.operationId, record);
    }
  }
  return { operations: result, duplicates };
}

function normalizePathname(value) {
  return String(value)
    .split('?', 1)[0]
    .replace(/\{[^}]+\}/g, '{}')
    .toLowerCase();
}

function docsPathFromParent(parentUrl) {
  return `content/docs${parentUrl}`;
}

function metaRouteLeaf(value) {
  if (typeof value !== 'string' || value.startsWith('---')) return null;
  const markdownLink = value.match(/^\[[^\]]+\]\(([^)]+)\)$/);
  const target = markdownLink?.[1] ?? value;
  return target.split(/[?#]/, 1)[0].replace(/^\.\//, '').replace(/^\//, '');
}

function metaRouteLeaves(pages) {
  const leaves = [];
  for (const page of pages ?? []) {
    if (typeof page === 'string') {
      const leaf = metaRouteLeaf(page);
      if (leaf) leaves.push(leaf);
      continue;
    }
    if (page && typeof page === 'object') {
      leaves.push(...metaRouteLeaves(page.pages));
    }
  }
  return leaves;
}

function liveVisibleOperationIds(manifest, pagesByUrl) {
  const result = new Map();
  for (const entry of manifest.entries ?? []) {
    const ordered = [];
    for (const page of entry.pageGraph?.pages ?? []) {
      const evidence = pagesByUrl.get(page.url.replace(/\.html(?=$|[?#])/, ''));
      if (evidence?.sourceResolution?.type !== 'openapi') continue;
      const operationId = evidence.sourceResolution.targetOperationId;
      const laneId = evidence.sourceResolution.laneId;
      if (
        operationId &&
        laneId &&
        !ordered.some(
          (record) =>
            record.operationId === operationId && record.laneId === laneId,
        )
      ) {
        ordered.push({ operationId, laneId });
      }
    }
    for (const { operationId, laneId } of ordered) {
      const values = result.get(laneId) ?? [];
      if (!values.includes(operationId)) values.push(operationId);
      result.set(laneId, values);
    }
  }
  return result;
}

function issue(code, severity, message, details = {}) {
  return { code, severity, message, ...details };
}

function renderMarkdown(report) {
  const lines = [
    '# API Center OpenAPI Audit',
    '',
    '> Generated by `scripts/audit-api-center-openapi.mjs`. Do not edit by hand.',
    '',
    `- Lanes: ${report.counts.lanes}`,
    `- Reachable operations: ${report.counts.reachableOperations}`,
    `- Live sidebar operations: ${report.counts.liveSidebarOperations}`,
    `- Errors: ${report.counts.errors}`,
    `- Warnings: ${report.counts.warnings}`,
    '',
  ];
  for (const lane of report.lanes) {
    lines.push(
      `## ${lane.laneId}`,
      '',
      `- Source: \`${lane.sourcePath ?? ''}\``,
      `- Reachable operations: ${lane.reachableOperationIds.length}`,
      `- Live sidebar operations: ${lane.liveSidebarOperationIds.length}`,
      `- Lane operations: ${lane.laneOperationIds.length}`,
      `- Extra lane operations outside the live reachable set: ${lane.extraLaneOperationIds.length}`,
      '',
    );
    if (lane.issues.length === 0) {
      lines.push('- Pass.', '');
    } else {
      lines.push(
        ...lane.issues.map(
          (entry) =>
            `- **${entry.severity}** \`${entry.code}\`: ${entry.message}`,
        ),
        '',
      );
    }
  }
  return `${lines.join('\n')}\n`;
}

/**
 * @param {object} options
 * @param {string} options.repoRoot
 * @param {string} options.oldRoot
 * @param {any} options.manifest
 * @param {readonly any[]} options.lanes
 * @param {string} options.sourceTextRegistry
 * @param {string | null} [options.scope]
 */
export async function auditApiCenterOpenApi({
  repoRoot,
  oldRoot,
  manifest,
  lanes,
  sourceTextRegistry,
  scope = null,
}) {
  const logicalPages = (manifest.pageEvidence ?? []).filter(
    (page) =>
      !page.aliasOf &&
      page.sourceResolution?.type === 'openapi' &&
      (!scope || page.sourceResolution.route?.scopeKey === scope),
  );
  const pagesByUrl = new Map();
  for (const page of manifest.pageEvidence ?? []) {
    pagesByUrl.set(page.requestedUrl.replace(/\.html(?=$|[?#])/, ''), page);
  }
  const visibleByLane = liveVisibleOperationIds(manifest, pagesByUrl);
  const laneById = new Map(lanes.map((lane) => [lane.id, lane]));
  const grouped = new Map();
  for (const page of logicalPages) {
    const laneId = page.sourceResolution.laneId;
    const values = grouped.get(laneId) ?? [];
    values.push(page);
    grouped.set(laneId, values);
  }
  const results = [];
  for (const [laneId, pages] of [...grouped].sort(([left], [right]) =>
    left.localeCompare(right),
  )) {
    const issues = [];
    const lane = laneById.get(laneId);
    const sourcePath = pages[0]?.sourceResolution?.targetPath ?? null;
    const legacySourcePath = pages[0]?.sourceResolution?.sourcePath ?? null;
    let targetOperations = new Map();
    let legacyOperations = new Map();
    if (!lane) {
      issues.push(
        issue('missing-lane', 'error', `Lane ${laneId} is not registered.`),
      );
    }
    if (!sourcePath || !(await exists(path.resolve(repoRoot, sourcePath)))) {
      issues.push(
        issue('missing-target-yaml', 'error', `Missing ${sourcePath}.`),
      );
    } else {
      const parsed = operations(
        yaml.load(
          await fs.readFile(path.resolve(repoRoot, sourcePath), 'utf8'),
        ),
      );
      targetOperations = parsed.operations;
      for (const duplicate of parsed.duplicates) {
        issues.push(
          issue(
            'duplicate-operation-id',
            'error',
            `Target YAML repeats operationId ${duplicate}.`,
          ),
        );
      }
      for (const operation of targetOperations.values()) {
        if (
          operation.description.includes('\n') ||
          /[`>[]/.test(operation.description)
        ) {
          issues.push(
            issue(
              'operation-description-is-markdown',
              'warning',
              `${operation.operationId} has block/Markdown syntax in its short description.`,
            ),
          );
        }
      }
    }
    if (
      legacySourcePath &&
      oldRoot &&
      (await exists(path.resolve(oldRoot, legacySourcePath)))
    ) {
      legacyOperations = operations(
        yaml.load(
          await fs.readFile(path.resolve(oldRoot, legacySourcePath), 'utf8'),
        ),
      ).operations;
    } else {
      issues.push(
        issue(
          'missing-legacy-yaml',
          'error',
          `Missing legacy YAML ${legacySourcePath}.`,
        ),
      );
    }
    const reachableOperationIds = [];
    for (const page of pages) {
      const resolution = page.sourceResolution;
      const targetId = resolution.targetOperationId;
      const legacyId = resolution.legacyOperationId;
      if (!reachableOperationIds.includes(targetId)) {
        reachableOperationIds.push(targetId);
      }
      const targetOperation = targetOperations.get(targetId);
      const legacyOperation = legacyOperations.get(legacyId);
      const laneOperation = lane?.operations?.[targetId];
      if (!targetOperation) {
        issues.push(
          issue(
            'missing-target-operation',
            'error',
            `Missing target operation ${targetId}.`,
          ),
        );
      }
      if (!legacyOperation) {
        issues.push(
          issue(
            'missing-legacy-operation',
            'error',
            `Missing legacy operation ${legacyId}.`,
          ),
        );
      }
      if (!laneOperation) {
        issues.push(
          issue('missing-lane-operation', 'error', `Lane omits ${targetId}.`),
        );
      }
      if (
        targetOperation &&
        legacyOperation &&
        (targetOperation.method !== legacyOperation.method ||
          normalizePathname(targetOperation.pathname) !==
            normalizePathname(legacyOperation.pathname))
      ) {
        issues.push(
          issue(
            'operation-method-path-drift',
            'error',
            `${legacyId} no longer maps to the same method/path as ${targetId}.`,
          ),
        );
      }
      const expectedRouteLeaf = resolution.targetRoute
        ?.split('/')
        .filter(Boolean)
        .at(-1);
      if (laneOperation && laneOperation.routeLeaf !== expectedRouteLeaf) {
        issues.push(
          issue(
            'lane-route-drift',
            'error',
            `${targetId} maps to ${laneOperation.routeLeaf}, expected ${expectedRouteLeaf}.`,
          ),
        );
      }
    }
    if (sourcePath && !sourceTextRegistry.includes(sourcePath)) {
      issues.push(
        issue(
          'missing-bundled-source',
          'error',
          `${sourcePath} is absent from source-text.server.ts.`,
        ),
      );
    }
    const laneOperationIds = Object.keys(lane?.operations ?? {});
    const liveSidebarOperationIds = (visibleByLane.get(laneId) ?? []).filter(
      (operationId) => reachableOperationIds.includes(operationId),
    );
    const extraLaneOperationIds = laneOperationIds.filter(
      (operationId) => !reachableOperationIds.includes(operationId),
    );
    let metaPages = [];
    if (lane) {
      const docsRoot = docsPathFromParent(lane.parentUrl['zh-CN']);
      const metaPath = `${docsRoot}/meta.json`;
      const hasIndex =
        (await exists(path.resolve(repoRoot, `${docsRoot}/index.mdx`))) ||
        (await exists(path.resolve(repoRoot, `${docsRoot}/index.md`)));
      if (!hasIndex) {
        issues.push(
          issue(
            'missing-entry-page',
            'error',
            `Missing ${docsRoot}/index.mdx.`,
          ),
        );
      }
      if (!(await exists(path.resolve(repoRoot, metaPath)))) {
        issues.push(issue('missing-meta', 'error', `Missing ${metaPath}.`));
      } else {
        const meta = JSON.parse(
          await fs.readFile(path.resolve(repoRoot, metaPath), 'utf8'),
        );
        metaPages = metaRouteLeaves(meta.pages);
        for (const operationId of liveSidebarOperationIds) {
          const routeLeaf = lane.operations[operationId]?.routeLeaf;
          if (routeLeaf && !metaPages.includes(routeLeaf)) {
            issues.push(
              issue(
                'missing-visible-meta-route',
                'error',
                `Live sidebar route ${routeLeaf} is absent from ${metaPath}.`,
              ),
            );
          }
        }
        const visibleLeaves = new Set(
          liveSidebarOperationIds.map(
            (operationId) => lane.operations[operationId]?.routeLeaf,
          ),
        );
        const supplementalMetaLeaves = new Set(
          (manifest.pageEvidence ?? []).flatMap((page) => {
            const supplement = page.sourceResolution?.apiReferenceSupplement;
            if (supplement?.parentRoute !== lane.parentUrl['zh-CN']) return [];
            return (supplement.navigationPagePlacements ?? []).map(
              (placement) => placement.page,
            );
          }),
        );
        const extraMeta = metaPages.filter(
          (routeLeaf) =>
            laneOperationIds.some(
              (operationId) =>
                lane.operations[operationId].routeLeaf === routeLeaf,
            ) &&
            !visibleLeaves.has(routeLeaf) &&
            !supplementalMetaLeaves.has(routeLeaf),
        );
        if (extraMeta.length > 0) {
          issues.push(
            issue(
              'meta-exposes-non-sidebar-operations',
              'warning',
              `Meta exposes OpenAPI routes not present in the live sidebar: ${extraMeta.join(', ')}.`,
              { routeLeaves: extraMeta },
            ),
          );
        }
      }
    }
    results.push({
      laneId,
      sourcePath,
      legacySourcePath,
      reachableOperationIds,
      liveSidebarOperationIds,
      laneOperationIds,
      extraLaneOperationIds,
      metaPages,
      issues,
    });
  }
  const allIssues = results.flatMap((result) => result.issues);
  return stableJson({
    schemaVersion: 1,
    scope,
    counts: {
      lanes: results.length,
      reachableOperations: logicalPages.length,
      liveSidebarOperations: results.reduce(
        (sum, result) => sum + result.liveSidebarOperationIds.length,
        0,
      ),
      errors: allIssues.filter((entry) => entry.severity === 'error').length,
      warnings: allIssues.filter((entry) => entry.severity === 'warning')
        .length,
    },
    lanes: results,
  });
}

export async function writeOpenApiAudit({
  repoRoot,
  report,
  mode,
  jsonPath,
  markdownPath,
}) {
  const files = [
    [jsonPath, json(report)],
    [markdownPath, renderMarkdown(report)],
  ];
  for (const [relative, contents] of files) {
    const absolute = path.resolve(repoRoot, relative);
    if (mode === 'check') {
      const actual = await fs.readFile(absolute, 'utf8');
      if (actual !== contents)
        throw new Error(`Generated file is stale: ${relative}`);
    } else if (mode === 'write') {
      await fs.mkdir(path.dirname(absolute), { recursive: true });
      await fs.writeFile(absolute, contents, 'utf8');
    }
  }
}
