import { execFileSync } from 'node:child_process';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, describe, expect, it } from 'vitest';

const SCRIPT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  'html-to-md-migration.mjs',
);

const tempDirs: string[] = [];

async function makeTempDir() {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'html-to-md-migration-'));
  tempDirs.push(dir);
  return dir;
}

async function writeFixture(filePath: string, contents: string) {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, contents, 'utf8');
}

async function pathExists(filePath: string) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function readJson(filePath: string) {
  return JSON.parse(await fs.readFile(filePath, 'utf8')) as {
    navScope?: Record<string, unknown>;
    pages?: string[];
    title?: string;
  };
}

function runMigration(args: string[]) {
  return execFileSync(process.execPath, [SCRIPT, ...args], {
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  });
}

function runMigrationFailure(args: string[]) {
  try {
    runMigration(args);
  } catch (error) {
    const execError = error as Error & {
      stderr?: Buffer | string;
      stdout?: Buffer | string;
    };
    return `${execError.stdout ?? ''}${execError.stderr ?? ''}`;
  }

  throw new Error('Expected migration command to fail.');
}

function ditaPage(title: string) {
  return `<!doctype html>
<html>
  <head><meta name="description" content="${title} description."></head>
  <body>
    <main>
      <article>
        <h1>${title}</h1>
        <div class="body">
          <p class="shortdesc">${title} summary.</p>
          <section id="details">
            <h2>Details</h2>
            <p>Call <code>join</code> from this page.</p>
          </section>
        </div>
      </article>
    </main>
  </body>
</html>`;
}

async function writeDitaFixture(sourceDir: string) {
  await writeFixture(
    path.join(sourceDir, 'index.html'),
    `<!doctype html>
<html>
  <body>
    <nav class="toc">
      <ul>
        <li>
          <span>API Reference</span>
          <ul>
            <li><a href="API/overview.html">Overview</a></li>
            <li><a href="API/class_video_canvas.html">VideoCanvas</a></li>
          </ul>
        </li>
      </ul>
    </nav>
  </body>
</html>`,
  );
  await writeFixture(
    path.join(sourceDir, 'API', 'overview.html'),
    ditaPage('Overview'),
  );
  await writeFixture(
    path.join(sourceDir, 'API', 'class_video_canvas.html'),
    ditaPage('VideoCanvas'),
  );
}

async function expectLaneDryRunAndMigration({
  detected,
  expectedMetaPages,
  expectedPageContents,
  outputDir,
  platform,
  product,
  sourceDir,
}: {
  detected: string;
  expectedMetaPages: string[];
  expectedPageContents: Record<string, string[]>;
  outputDir: string;
  platform: string;
  product: string;
  sourceDir: string;
}) {
  const dryOutputDir = `${outputDir}-dry`;
  const dryOutput = runMigration([
    '--source',
    sourceDir,
    '--output',
    dryOutputDir,
    '--product',
    product,
    '--platform',
    platform,
    '--dry-run',
  ]);

  expect(dryOutput).toContain(`Detected source type: ${detected}`);
  expect(dryOutput).toContain('Planned output paths');
  expect(dryOutput).toContain(path.join(dryOutputDir, 'index.mdx'));
  expect(dryOutput).toContain(path.join(dryOutputDir, 'meta.json'));
  for (const relativePath of Object.keys(expectedPageContents)) {
    expect(dryOutput).toContain(path.join(dryOutputDir, relativePath));
  }
  await expect(pathExists(dryOutputDir)).resolves.toBe(false);

  const output = runMigration([
    '--source',
    sourceDir,
    '--output',
    outputDir,
    '--product',
    product,
    '--platform',
    platform,
  ]);

  expect(output).toContain(`Detected:  ${detected}`);
  await expect(pathExists(path.join(outputDir, 'index.mdx'))).resolves.toBe(
    true,
  );
  const meta = await readJson(path.join(outputDir, 'meta.json'));
  expect(meta.pages).toEqual(expectedMetaPages);

  for (const [relativePath, snippets] of Object.entries(expectedPageContents)) {
    const contents = await fs.readFile(
      path.join(outputDir, relativePath),
      'utf8',
    );
    for (const snippet of snippets) expect(contents).toContain(snippet);
  }
}

async function writeTypeDocFixture(sourceDir: string) {
  await writeFixture(
    path.join(sourceDir, 'index.html'),
    `<!doctype html>
<html>
  <body>
    <main>
      <h1>TypeDoc API</h1>
      <p>Generated by TypeDoc.</p>
      <nav>
        <a href="modules.html">Modules</a>
        <a href="classes/Client.html#connect">Client</a>
      </nav>
    </main>
  </body>
</html>`,
  );
  await writeFixture(
    path.join(sourceDir, 'modules.html'),
    `<!doctype html>
<html>
  <head><meta name="description" content="TypeScript module list."></head>
  <body>
    <main>
      <h1>Modules</h1>
      <p>Open the <a href="classes/Client.html#connect">Client class</a>.</p>
      <ul><li><code>createClient</code></li></ul>
    </main>
  </body>
</html>`,
  );
  await writeFixture(
    path.join(sourceDir, 'classes', 'Client.html'),
    `<!doctype html>
<html>
  <body>
    <header>
      <div class="tsd-page-title"><h1>Class Client</h1></div>
    </header>
    <div class="col-content">
      <section class="tsd-panel tsd-comment">
        <div class="tsd-comment tsd-typography">
          <p>Controls a realtime session.</p>
        </div>
      </section>
      <section class="tsd-panel-group tsd-member-group">
        <h2>Methods</h2>
        <section class="tsd-panel tsd-member tsd-kind-method">
          <a id="connect" class="tsd-anchor"></a>
          <h3>connect</h3>
          <ul class="tsd-signatures">
            <li class="tsd-signature tsd-kind-icon">connect(appId: <span class="tsd-signature-type">string</span>): <span class="tsd-signature-type">Promise</span>&lt;void&gt;</li>
          </ul>
          <ul class="tsd-descriptions">
            <li class="tsd-description">
              <div class="tsd-comment tsd-typography">
                <p>Call <code>connect</code> before publishing.</p>
              </div>
              <h4 class="tsd-parameters-title">Parameters</h4>
              <ul class="tsd-parameters">
                <li>
                  <h5>appId: <span class="tsd-signature-type">string</span></h5>
                  <div class="tsd-comment tsd-typography"><p>Agora application ID.</p></div>
                </li>
              </ul>
              <h4 class="tsd-returns-title">Returns <span class="tsd-signature-type">Promise</span>&lt;void&gt;</h4>
            </li>
          </ul>
        </section>
        <section class="tsd-panel tsd-member tsd-kind-type-alias">
          <a name="joinroomparams" class="tsd-anchor"></a>
          <h3>Join<wbr>Room<wbr>Params</h3>
          <div class="tsd-signature tsd-kind-icon">JoinRoomParams: { hotKeys?: Partial&lt;HotKeys&gt;; roomToken: string }</div>
          <div class="tsd-comment tsd-typography">
            <p>Options used to join a room.</p>
            <ul>
              <li>
                <p><strong>hotKeys?</strong>: <em>Partial&lt;HotKeys&gt;</em></p>
                <p>Custom shortcuts. Defaults to:</p>
                <table>
                  <thead><tr><th>Key</th><th>Effect</th></tr></thead>
                  <tbody>
                    <tr><td>Backspace</td><td>Delete selected objects</td></tr>
                    <tr><td>Ctrl + Z</td><td>Undo</td></tr>
                  </tbody>
                </table>
                <p>Pass an empty object to disable shortcuts.</p>
              </li>
            </ul>
            <ol>
              <li>
                <p>Configure shortcuts in order.</p>
                <table>
                  <thead><tr><th>Step</th><th>Action</th></tr></thead>
                  <tbody><tr><td>1</td><td>Choose a key</td></tr></tbody>
                </table>
              </li>
            </ol>
          </div>
          <div class="tsd-type-declaration">
            <h4>Type declaration</h4>
            <ul class="tsd-parameters">
              <li class="tsd-parameter">
                <h5><span class="tsd-flag ts-flagOptional">Optional</span> hot<wbr>Keys<span class="tsd-signature-symbol">?: </span><span class="tsd-signature-type">Partial&lt;HotKeys&gt;</span></h5>
                <div class="tsd-comment tsd-typography">
                  <p>Overrides the default shortcut map.</p>
                  <table>
                    <thead><tr><th>Key</th><th>Default action</th></tr></thead>
                    <tbody><tr><td>Backspace</td><td>Delete selection</td></tr></tbody>
                  </table>
                  <ul>
                    <li><p>Use platform-native key names.</p></li>
                  </ul>
                  <dl><dt>since</dt><dd><p>2.0.0</p></dd></dl>
                </div>
              </li>
              <li class="tsd-parameter">
                <h5>room<wbr>Token<span class="tsd-signature-symbol">: </span><span class="tsd-signature-type">string</span></h5>
                <div class="tsd-comment tsd-typography"><p>Token used to join the room.</p></div>
              </li>
            </ul>
          </div>
        </section>
      </section>
    </div>
  </body>
</html>`,
  );
}

async function writeDoxygenFixture(sourceDir: string) {
  await writeFixture(path.join(sourceDir, 'doxygen.css'), '/* marker */');
  await writeFixture(
    path.join(sourceDir, 'index.html'),
    `<!doctype html>
<html>
  <body>
    <div class="contents">
      <h1>Doxygen API</h1>
      <p>Generated by Doxygen.</p>
      <a href="annotated.html">Class Index</a>
      <a href="class_agora_1_1rtc_1_1_client.html#join">Client</a>
    </div>
  </body>
</html>`,
  );
  await writeFixture(
    path.join(sourceDir, 'annotated.html'),
    `<!doctype html>
<html>
  <body>
    <div class="contents">
      <div class="title">Class Index</div>
      <p>See <a href="class_agora_1_1rtc_1_1_client.html#join">Client</a>.</p>
    </div>
  </body>
</html>`,
  );
  await writeFixture(
    path.join(sourceDir, 'class_agora_1_1rtc_1_1_client.html'),
    `<!doctype html>
<html>
  <body>
    <div class="contents">
      <div class="title">Client Class Reference</div>
      <p>Back to <a href="annotated.html">all classes</a>.</p>
      <a id="join"></a>
      <h2>join</h2>
      <table>
        <tr><th>Parameter</th><th>Description</th></tr>
        <tr><td>channel</td><td>Channel name</td></tr>
      </table>
    </div>
  </body>
</html>`,
  );
}

async function writeIosFixture(sourceDir: string) {
  await writeFixture(
    path.join(sourceDir, 'index.html'),
    `<!doctype html>
<html>
  <body>
    <main>
      <h1>Jazzy API</h1>
      <p>Generated by jazzy.</p>
      <a href="Classes/index.html">Classes</a>
      <a href="Classes/AgoraRtcEngineKit.html">AgoraRtcEngineKit</a>
      <a href="Protocols/AgoraRtcEngineDelegate.html#events">Delegate</a>
    </main>
  </body>
</html>`,
  );
  await writeFixture(
    path.join(sourceDir, 'hierarchy.html'),
    '<!doctype html><html><body><main><h1>Hierarchy</h1><p>iOS hierarchy.</p></main></body></html>',
  );
  await writeFixture(
    path.join(sourceDir, 'Classes', 'index.html'),
    `<!doctype html>
<html>
  <body>
    <article class="main-content">
      <h1>Classes</h1>
      <p>iOS classes index.</p>
      <a href="AgoraRtcEngineKit.html">Engine class</a>
    </article>
  </body>
</html>`,
  );
  await writeFixture(
    path.join(sourceDir, 'Classes', 'AgoraRtcEngineKit.html'),
    `<!doctype html>
<html>
  <body>
    <article class="main-content">
      <h1>AgoraRtcEngineKit</h1>
      <p>Engine class with <a href="../Protocols/AgoraRtcEngineDelegate.html#events">delegate callbacks</a>.</p>
      <p>Back to the <a href="index.html">classes overview</a>.</p>
      <h2><a name="sharedengine"></a>sharedEngine</h2>
      <p>Creates an engine instance.</p>
    </article>
  </body>
</html>`,
  );
  await writeFixture(
    path.join(sourceDir, 'Protocols', 'AgoraRtcEngineDelegate.html'),
    `<!doctype html>
<html>
  <body>
    <article class="main-content">
      <h1>AgoraRtcEngineDelegate</h1>
      <a id="events"></a>
      <p>Receives event callbacks.</p>
    </article>
  </body>
</html>`,
  );
}

async function writeDartdocFixture(sourceDir: string) {
  await writeFixture(path.join(sourceDir, 'index.json'), '{"marker":true}');
  await writeFixture(
    path.join(sourceDir, 'index.html'),
    `<!doctype html>
<html>
  <body>
    <main>
      <h1>Dartdoc API</h1>
      <p>Generated by dartdoc.</p>
      <a href="library-index.html">Libraries</a>
      <a href="agora_rtc/agora_rtc-library.html#RtcEngine">agora_rtc</a>
    </main>
  </body>
</html>`,
  );
  await writeFixture(
    path.join(sourceDir, 'library-index.html'),
    `<!doctype html>
<html>
  <body>
    <main>
      <h1>Libraries</h1>
      <p>See <a href="agora_rtc/agora_rtc-library.html#RtcEngine">RtcEngine</a>.</p>
    </main>
  </body>
</html>`,
  );
  await writeFixture(
    path.join(sourceDir, 'agora_rtc', 'agora_rtc-library.html'),
    `<!doctype html>
<html>
  <body>
    <main>
      <h1>agora_rtc library</h1>
      <section id="RtcEngine">
        <h2>RtcEngine</h2>
        <p>Primary Dart RTC engine.</p>
        <ol><li>Initialize the engine.</li></ol>
      </section>
      <section id="guides">
        <h2>Guides</h2>
        <ul>
          <li>
            <a href="#setup">Setup</a>
            <ul><li><a href="#advanced">Advanced</a></li></ul>
          </li>
        </ul>
      </section>
    </main>
  </body>
</html>`,
  );
}

describe('html-to-md-migration', () => {
  afterEach(async () => {
    await Promise.all(
      tempDirs
        .splice(0)
        .map((dir) => fs.rm(dir, { force: true, recursive: true })),
    );
  });

  it('migrates a supported DITA-OT API directory', async () => {
    const rootDir = await makeTempDir();
    const sourceDir = path.join(rootDir, 'source');
    const outputDir = path.join(rootDir, 'output');
    await writeDitaFixture(sourceDir);

    const output = runMigration([
      '--source',
      sourceDir,
      '--output',
      outputDir,
      '--product',
      'rtc',
      '--platform',
      'android',
    ]);

    expect(output).toContain(
      'Detected:  DITA-OT/Oxygen API reference (API/ directory)',
    );
    expect(output).toContain('Files:     2');
    await expect(
      fs.readFile(path.join(outputDir, 'index.mdx'), 'utf8'),
    ).resolves.toContain('ANDROID API Reference');
    await expect(
      fs.readFile(path.join(outputDir, 'meta.json'), 'utf8'),
    ).resolves.toContain('"overview"');
    await expect(
      fs.readFile(path.join(outputDir, 'overview.mdx'), 'utf8'),
    ).resolves.toContain('title: "Overview"');
    await expect(
      fs.readFile(path.join(outputDir, 'class-video-canvas.mdx'), 'utf8'),
    ).resolves.toContain('Call `join` from this page.');
  });

  it('prints detected source type, file count, and planned paths in dry-run without writing', async () => {
    const rootDir = await makeTempDir();
    const sourceDir = path.join(rootDir, 'source');
    const outputDir = path.join(rootDir, 'dry-output');
    await writeDitaFixture(sourceDir);

    const output = runMigration([
      '--source',
      sourceDir,
      '--output',
      outputDir,
      '--product',
      'rtc',
      '--platform',
      'android',
      '--dry-run',
    ]);

    expect(output).toContain(
      'Detected source type: DITA-OT/Oxygen API reference (API/ directory)',
    );
    expect(output).toContain('File count: 2');
    expect(output).toContain('Planned output paths');
    expect(output).toContain(path.join(outputDir, 'index.mdx'));
    expect(output).toContain(path.join(outputDir, 'overview.mdx'));
    await expect(pathExists(outputDir)).resolves.toBe(false);
  });

  it('migrates TypeDoc output with dry-run planning and rewritten links', async () => {
    const rootDir = await makeTempDir();
    const sourceDir = path.join(rootDir, 'typedoc-source');
    const outputDir = path.join(rootDir, 'output');
    await writeTypeDocFixture(sourceDir);

    await expectLaneDryRunAndMigration({
      detected: 'TypeDoc HTML reference',
      expectedMetaPages: ['index', 'modules', 'classes'],
      expectedPageContents: {
        'classes/client.mdx': [
          'title: "Client"',
          '<a id="connect"></a>',
          '## Methods',
          '### connect',
          '```ts\nconnect(appId: string): Promise<void>\n```',
          'Call `connect` before publishing.',
          '#### Parameters',
          '| appId: string | Agora application ID. |',
          '#### Returns',
          'Returns Promise &lt;void&gt;',
          '<a id="joinroomparams"></a>',
          '### JoinRoomParams',
          '- **hotKeys?**: *Partial&lt;HotKeys&gt;*',
          '  Custom shortcuts. Defaults to:',
          '  | Key | Effect |',
          '  | Backspace | Delete selected objects |',
          '  | Ctrl + Z | Undo |',
          '  Pass an empty object to disable shortcuts.',
          '1. Configure shortcuts in order.',
          '   | Step | Action |',
          '   | 1 | Choose a key |',
          '#### Type declaration',
          '##### `hotKeys?: Partial<HotKeys>`',
          'Overrides the default shortcut map.',
          '| Key | Default action |',
          '| Backspace | Delete selection |',
          '- Use platform-native key names.',
          '###### `since`',
          '2.0.0',
          '##### `roomToken: string`',
          'Token used to join the room.',
        ],
        'modules.mdx': [
          '[Client class](/api-reference/web/typescript/classes/client#connect)',
        ],
      },
      outputDir,
      platform: 'typescript',
      product: 'web',
      sourceDir,
    });

    const clientOutput = await fs.readFile(
      path.join(outputDir, 'classes/client.mdx'),
      'utf8',
    );
    expect(clientOutput).not.toContain('##### `Optional hotKeys');
    expect(clientOutput).not.toMatch(/^#{7,}\s/m);
  });

  it('creates a scoped sidebar for Whiteboard Web API output', async () => {
    const rootDir = await makeTempDir();
    const sourceDir = path.join(rootDir, 'typedoc-source');
    const outputDir = path.join(rootDir, 'output');
    await writeTypeDocFixture(sourceDir);

    runMigration([
      '--source',
      sourceDir,
      '--output',
      outputDir,
      '--product',
      'whiteboard',
      '--platform',
      'web',
    ]);

    await expect(
      readJson(path.join(outputDir, 'meta.json')),
    ).resolves.toMatchObject({ navScope: {} });
  });

  it('migrates Doxygen/Javadoc output with dry-run planning and rewritten links', async () => {
    const rootDir = await makeTempDir();
    const sourceDir = path.join(rootDir, 'doxygen-source');
    const outputDir = path.join(rootDir, 'output');
    await writeDoxygenFixture(sourceDir);

    await expectLaneDryRunAndMigration({
      detected: 'Doxygen/Javadoc HTML reference',
      expectedMetaPages: [
        'index',
        'annotated',
        'class-agora-1-1rtc-1-1-client',
      ],
      expectedPageContents: {
        'annotated.mdx': [
          'title: "Class Index"',
          '[Client](/api-reference/rtc/cpp/class-agora-1-1rtc-1-1-client#join)',
        ],
        'class-agora-1-1rtc-1-1-client.mdx': [
          'title: "Client Class Reference"',
          '[all classes](/api-reference/rtc/cpp/annotated)',
          '<a id="join"></a>',
          '| Parameter | Description |',
          '| channel | Channel name |',
        ],
      },
      outputDir,
      platform: 'cpp',
      product: 'rtc',
      sourceDir,
    });
  });

  it('migrates iOS doc-generator output with dry-run planning and rewritten links', async () => {
    const rootDir = await makeTempDir();
    const sourceDir = path.join(rootDir, 'ios-source');
    const outputDir = path.join(rootDir, 'output');
    await writeIosFixture(sourceDir);

    await expectLaneDryRunAndMigration({
      detected: 'iOS-doc-generator HTML reference',
      expectedMetaPages: ['index', 'classes', 'protocols', 'hierarchy'],
      expectedPageContents: {
        'classes/index.mdx': [
          'title: "Classes"',
          'iOS classes index.',
          '[Engine class](/api-reference/rtc/ios/classes/agora-rtc-engine-kit)',
        ],
        'classes/agora-rtc-engine-kit.mdx': [
          'title: "AgoraRtcEngineKit"',
          '[delegate callbacks](/api-reference/rtc/ios/protocols/agora-rtc-engine-delegate#events)',
          '[classes overview](/api-reference/rtc/ios/classes)',
          '<a id="sharedengine"></a>',
          'Creates an engine instance.',
        ],
        'protocols/agora-rtc-engine-delegate.mdx': [
          'title: "AgoraRtcEngineDelegate"',
          '<a id="events"></a>',
          'Receives event callbacks.',
        ],
      },
      outputDir,
      platform: 'ios',
      product: 'rtc',
      sourceDir,
    });
  });

  it('migrates Dartdoc output with dry-run planning and rewritten links', async () => {
    const rootDir = await makeTempDir();
    const sourceDir = path.join(rootDir, 'dartdoc-source');
    const outputDir = path.join(rootDir, 'output');
    await writeDartdocFixture(sourceDir);

    await expectLaneDryRunAndMigration({
      detected: 'Dartdoc HTML reference',
      expectedMetaPages: ['index', 'library-index', 'agora-rtc'],
      expectedPageContents: {
        'agora-rtc/agora-rtc-library.mdx': [
          'title: "agora_rtc library"',
          '<a id="RtcEngine"></a>',
          'Primary Dart RTC engine.',
          '1. Initialize the engine.',
          '- [Setup](#setup)\n\n  - [Advanced](#advanced)',
        ],
        'library-index.mdx': [
          '[RtcEngine](/api-reference/rtc/dart/agora-rtc/agora-rtc-library#RtcEngine)',
        ],
      },
      outputDir,
      platform: 'dart',
      product: 'rtc',
      sourceDir,
    });
  });

  it('fails unsupported sources without API with a clear actionable error', async () => {
    const rootDir = await makeTempDir();
    const sourceDir = path.join(rootDir, 'unsupported-source');
    const outputDir = path.join(rootDir, 'output');
    await writeFixture(
      path.join(sourceDir, 'index.html'),
      '<!doctype html><html><body><h1>RESTful API</h1></body></html>',
    );

    const output = runMigrationFailure([
      '--source',
      sourceDir,
      '--output',
      outputDir,
      '--product',
      'cloud-recording',
      '--platform',
      'restful',
    ]);

    expect(output).toContain(
      'Unsupported source structure: RESTful/OpenAPI or other unsupported source layout.',
    );
    expect(output).toContain('root-level HTML file(s), but no API/');
    expect(output).toContain(
      'Supported lanes: DITA-OT/Oxygen, TypeDoc, Doxygen/Javadoc, iOS doc-generator/Jazzy/appledoc, and Dartdoc generated HTML API references.',
    );
    expect(output).not.toContain('ENOENT');
  });

  it('refuses dangerous output paths before deleting existing files', async () => {
    const rootDir = await makeTempDir();
    const sourceDir = path.join(rootDir, 'source');
    const sentinelPath = path.join(sourceDir, 'keep.txt');
    await writeDitaFixture(sourceDir);
    await writeFixture(sentinelPath, 'do not delete');

    const output = runMigrationFailure([
      '--source',
      sourceDir,
      '--output',
      sourceDir,
      '--product',
      'rtc',
      '--platform',
      'android',
    ]);

    expect(output).toContain('Refusing to delete protected output path');
    await expect(fs.readFile(sentinelPath, 'utf8')).resolves.toBe(
      'do not delete',
    );
  });

  it('refuses broad in-repo docs output paths before cleanup', async () => {
    const rootDir = await makeTempDir();
    const sourceDir = path.join(rootDir, 'source');
    await writeDitaFixture(sourceDir);

    const output = runMigrationFailure([
      '--source',
      sourceDir,
      '--output',
      path.resolve('content/docs/zh-CN/api-reference/rtc'),
      '--product',
      'rtc',
      '--platform',
      'android',
    ]);

    expect(output).toContain('Refusing to delete broad docs output path');
    expect(output).toContain('content/docs/zh-CN/api-reference/rtc/android');
  });

  it('refuses broad temporary and home-child output paths before cleanup', async () => {
    const rootDir = await makeTempDir();
    const sourceDir = path.join(rootDir, 'source');
    await writeDitaFixture(sourceDir);

    const tmpOutput = runMigrationFailure([
      '--source',
      sourceDir,
      '--output',
      '/tmp',
      '--product',
      'rtc',
      '--platform',
      'android',
    ]);
    expect(tmpOutput).toContain('Refusing to delete protected output path');

    const homeChildOutput = runMigrationFailure([
      '--source',
      sourceDir,
      '--output',
      path.join(os.homedir(), 'Downloads'),
      '--product',
      'rtc',
      '--platform',
      'android',
    ]);
    expect(homeChildOutput).toContain(
      'Refusing to delete broad home-directory child path',
    );
  });
});
