/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleTabRouteRouteImport } from './routes/$locale/$tab/route'
import { Route as ApiRefSplatRouteImport } from './routes/api-ref/$'
import { Route as DocSplatRouteImport } from './routes/doc/$'
import { Route as LlmsSplatRouteImport } from './routes/llms/$'
import { Route as LocaleTabIndexRouteImport } from './routes/$locale/$tab/index'
import { Route as LocaleTabSplatRouteImport } from './routes/$locale/$tab/$'
import { Route as Char91__staticChar93DocsSearchSplatRouteImport } from './routes/[__static]/docs-search/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/$locale/',
  path: '/$locale/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleTabRouteRoute = LocaleTabRouteRouteImport.update({
  id: '/$locale/$tab',
  path: '/$locale/$tab',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRefSplatRoute = ApiRefSplatRouteImport.update({
  id: '/api-ref/$',
  path: '/api-ref/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocSplatRoute = DocSplatRouteImport.update({
  id: '/doc/$',
  path: '/doc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsSplatRoute = LlmsSplatRouteImport.update({
  id: '/llms/$',
  path: '/llms/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleTabIndexRoute = LocaleTabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleTabRouteRoute,
} as any)
const LocaleTabSplatRoute = LocaleTabSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LocaleTabRouteRoute,
} as any)
const Char91__staticChar93DocsSearchSplatRoute =
  Char91__staticChar93DocsSearchSplatRouteImport.update({
    id: '/__static/docs-search/$',
    path: '/__static/docs-search/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/$tab': typeof LocaleTabRouteRouteWithChildren
  '/api-ref/$': typeof ApiRefSplatRoute
  '/doc/$': typeof DocSplatRoute
  '/llms/$': typeof LlmsSplatRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/$tab/$': typeof LocaleTabSplatRoute
  '/__static/docs-search/$': typeof Char91__staticChar93DocsSearchSplatRoute
  '/$locale/$tab/': typeof LocaleTabIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api-ref/$': typeof ApiRefSplatRoute
  '/doc/$': typeof DocSplatRoute
  '/llms/$': typeof LlmsSplatRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/$tab/$': typeof LocaleTabSplatRoute
  '/__static/docs-search/$': typeof Char91__staticChar93DocsSearchSplatRoute
  '/$locale/$tab': typeof LocaleTabIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/$tab': typeof LocaleTabRouteRouteWithChildren
  '/api-ref/$': typeof ApiRefSplatRoute
  '/doc/$': typeof DocSplatRoute
  '/llms/$': typeof LlmsSplatRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/$tab/$': typeof LocaleTabSplatRoute
  '/__static/docs-search/$': typeof Char91__staticChar93DocsSearchSplatRoute
  '/$locale/$tab/': typeof LocaleTabIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/$locale/$tab'
    | '/api-ref/$'
    | '/doc/$'
    | '/llms/$'
    | '/$locale/'
    | '/$locale/$tab/$'
    | '/__static/docs-search/$'
    | '/$locale/$tab/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/api-ref/$'
    | '/doc/$'
    | '/llms/$'
    | '/$locale'
    | '/$locale/$tab/$'
    | '/__static/docs-search/$'
    | '/$locale/$tab'
  id:
    | '__root__'
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/$locale/$tab'
    | '/api-ref/$'
    | '/doc/$'
    | '/llms/$'
    | '/$locale/'
    | '/$locale/$tab/$'
    | '/__static/docs-search/$'
    | '/$locale/$tab/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LocaleTabRouteRoute: typeof LocaleTabRouteRouteWithChildren
  ApiRefSplatRoute: typeof ApiRefSplatRoute
  DocSplatRoute: typeof DocSplatRoute
  LlmsSplatRoute: typeof LlmsSplatRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  Char91__staticChar93DocsSearchSplatRoute: typeof Char91__staticChar93DocsSearchSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/$locale'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$tab': {
      id: '/$locale/$tab'
      path: '/$locale/$tab'
      fullPath: '/$locale/$tab'
      preLoaderRoute: typeof LocaleTabRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-ref/$': {
      id: '/api-ref/$'
      path: '/api-ref/$'
      fullPath: '/api-ref/$'
      preLoaderRoute: typeof ApiRefSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$': {
      id: '/doc/$'
      path: '/doc/$'
      fullPath: '/doc/$'
      preLoaderRoute: typeof DocSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms/$': {
      id: '/llms/$'
      path: '/llms/$'
      fullPath: '/llms/$'
      preLoaderRoute: typeof LlmsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$tab/': {
      id: '/$locale/$tab/'
      path: '/'
      fullPath: '/$locale/$tab/'
      preLoaderRoute: typeof LocaleTabIndexRouteImport
      parentRoute: typeof LocaleTabRouteRoute
    }
    '/$locale/$tab/$': {
      id: '/$locale/$tab/$'
      path: '/$'
      fullPath: '/$locale/$tab/$'
      preLoaderRoute: typeof LocaleTabSplatRouteImport
      parentRoute: typeof LocaleTabRouteRoute
    }
    '/__static/docs-search/$': {
      id: '/__static/docs-search/$'
      path: '/__static/docs-search/$'
      fullPath: '/__static/docs-search/$'
      preLoaderRoute: typeof Char91__staticChar93DocsSearchSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LocaleTabRouteRouteChildren {
  LocaleTabSplatRoute: typeof LocaleTabSplatRoute
  LocaleTabIndexRoute: typeof LocaleTabIndexRoute
}

const LocaleTabRouteRouteChildren: LocaleTabRouteRouteChildren = {
  LocaleTabSplatRoute: LocaleTabSplatRoute,
  LocaleTabIndexRoute: LocaleTabIndexRoute,
}

const LocaleTabRouteRouteWithChildren = LocaleTabRouteRoute._addFileChildren(
  LocaleTabRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LocaleTabRouteRoute: LocaleTabRouteRouteWithChildren,
  ApiRefSplatRoute: ApiRefSplatRoute,
  DocSplatRoute: DocSplatRoute,
  LlmsSplatRoute: LlmsSplatRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  Char91__staticChar93DocsSearchSplatRoute:
    Char91__staticChar93DocsSearchSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
