/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangDocsIndexRouteImport } from './routes/$lang.docs.index'
import { Route as LlmsDotmdxDocsSplatRouteImport } from './routes/llms[.]mdx.docs.$'
import { Route as LangDocsSplatRouteImport } from './routes/$lang.docs.$'
import { Route as LangApiSearchRouteImport } from './routes/$lang.api.search'
import { Route as LangApiRefSplatRouteImport } from './routes/$lang.api-ref.$'

const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangDocsIndexRoute = LangDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => LangRoute,
} as any)
const LlmsDotmdxDocsSplatRoute = LlmsDotmdxDocsSplatRouteImport.update({
  id: '/llms.mdx/docs/$',
  path: '/llms.mdx/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LangDocsSplatRoute = LangDocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => LangRoute,
} as any)
const LangApiSearchRoute = LangApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => LangRoute,
} as any)
const LangApiRefSplatRoute = LangApiRefSplatRouteImport.update({
  id: '/api-ref/$',
  path: '/api-ref/$',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/api-ref/$': typeof LangApiRefSplatRoute
  '/$lang/api/search': typeof LangApiSearchRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
  '/$lang/docs/': typeof LangDocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/api-ref/$': typeof LangApiRefSplatRoute
  '/$lang/api/search': typeof LangApiSearchRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
  '/$lang/docs': typeof LangDocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/api-ref/$': typeof LangApiRefSplatRoute
  '/$lang/api/search': typeof LangApiSearchRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
  '/$lang/docs/': typeof LangDocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/$lang/'
    | '/$lang/api-ref/$'
    | '/$lang/api/search'
    | '/$lang/docs/$'
    | '/llms.mdx/docs/$'
    | '/$lang/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/$lang'
    | '/$lang/api-ref/$'
    | '/$lang/api/search'
    | '/$lang/docs/$'
    | '/llms.mdx/docs/$'
    | '/$lang/docs'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/$lang/'
    | '/$lang/api-ref/$'
    | '/$lang/api/search'
    | '/$lang/docs/$'
    | '/llms.mdx/docs/$'
    | '/$lang/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LlmsDotmdxDocsSplatRoute: typeof LlmsDotmdxDocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/docs/': {
      id: '/$lang/docs/'
      path: '/docs'
      fullPath: '/$lang/docs/'
      preLoaderRoute: typeof LangDocsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/llms.mdx/docs/$': {
      id: '/llms.mdx/docs/$'
      path: '/llms.mdx/docs/$'
      fullPath: '/llms.mdx/docs/$'
      preLoaderRoute: typeof LlmsDotmdxDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/docs/$': {
      id: '/$lang/docs/$'
      path: '/docs/$'
      fullPath: '/$lang/docs/$'
      preLoaderRoute: typeof LangDocsSplatRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/api/search': {
      id: '/$lang/api/search'
      path: '/api/search'
      fullPath: '/$lang/api/search'
      preLoaderRoute: typeof LangApiSearchRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/api-ref/$': {
      id: '/$lang/api-ref/$'
      path: '/api-ref/$'
      fullPath: '/$lang/api-ref/$'
      preLoaderRoute: typeof LangApiRefSplatRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangIndexRoute: typeof LangIndexRoute
  LangApiRefSplatRoute: typeof LangApiRefSplatRoute
  LangApiSearchRoute: typeof LangApiSearchRoute
  LangDocsSplatRoute: typeof LangDocsSplatRoute
  LangDocsIndexRoute: typeof LangDocsIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangIndexRoute: LangIndexRoute,
  LangApiRefSplatRoute: LangApiRefSplatRoute,
  LangApiSearchRoute: LangApiSearchRoute,
  LangDocsSplatRoute: LangDocsSplatRoute,
  LangDocsIndexRoute: LangDocsIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LlmsDotmdxDocsSplatRoute: LlmsDotmdxDocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
